(Troxid)vrep-api-python/examples/line_follower_pioneer.py", line 31, in right_color: Invalid type comment: List[int] [invalid-type-comment]
(Troxid)vrep-api-python/examples/line_follower_pioneer.py", line 36, in left_color: Invalid type comment: List[int] [invalid-type-comment]
(biolink)ontobio/ontobio/sim/api/semsearch.py", line 33, in __init__: Invalid type comment: AssociationSet [invalid-type-comment]
(pythonfoo)pythonfooLite/Level_07/linalg/gruppen.py", line 5, in Gruppe: Invalid type comment: Optional[Gruppe] [invalid-type-comment]
(SunDwarf)asyncqlio/asyncqlio/backends/sqlite3/aiosqlite3.py", line 128, in __init__: Invalid type comment: sqlite3.Connection [invalid-type-comment]
(albertyw)git-reviewers/git_reviewers/reviewers.py", line 23, in FindReviewers: Invalid type comment: (Config) -> None [invalid-type-comment]
(albertyw)git-reviewers/git_reviewers/reviewers.py", line 26, in FindReviewers: Invalid type comment: () -> typing.Counter[str] [invalid-type-comment]
(albertyw)git-reviewers/git_reviewers/reviewers.py", line 121, in FindFileLogReviewers: Invalid type comment: () -> typing.Counter[str] [invalid-type-comment]
(albertyw)git-reviewers/git_reviewers/reviewers.py", line 138, in FindHistoricalReviewers: Invalid type comment: () -> typing.Counter[str] [invalid-type-comment]
(albertyw)git-reviewers/git_reviewers/reviewers.py", line 182, in <module>: Invalid type comment: (Config) -> List[str] [invalid-type-comment]
(Jigsaw-Code)net-analysis/netanalysis/traffic/analysis/find_anomalies.py", line 268, in main: Invalid type comment: List[RegionDisruption] [invalid-type-comment]
(Jigsaw-Code)net-analysis/netanalysis/traffic/data/fetch_google_traffic.py", line 41, in main: Invalid type comment: modelTrafficRepository [invalid-type-comment]
(gajim)gajim/gajim/common/modules/base.py", line 40, in __init__: Invalid type comment: Callable [invalid-type-comment]
(erudit)eruditorg/tests/unit/base/test_viewcompat.py", line 80, in test_will_propagate_prepublication_ticket_received_in_querystring_for_article: Invalid type comment: Issue [invalid-type-comment]
(erudit)eruditorg/tests/unit/base/test_viewcompat.py", line 81, in test_will_propagate_prepublication_ticket_received_in_querystring_for_article: Invalid type comment: Journal [invalid-type-comment]
(trailofbits)manticore/examples/script/introduce_symbolic_bytes.py", line 78, in check_taint: Invalid type comment: capstone.CsInsn [invalid-type-comment]
(quantumlib)OpenFermion-Cirq/examples/examples_test.py", line 31, in test_can_run_examples_jupyter_notebook: Invalid type comment: Dict[str, Any] [invalid-type-comment]
(open-homeautomation)home-assistant/homeassistant/loader.py", line 36, in <module>: Invalid type comment: List[str] [invalid-type-comment]
(open-homeautomation)home-assistant/homeassistant/util/dt.py", line 122, in parse_datetime: Invalid type comment: Dict[str, Any] [invalid-type-comment]
(open-homeautomation)home-assistant/homeassistant/components/media_player/onkyo.py", line 29, in <module>: Invalid type comment: List[str] [invalid-type-comment]
(open-homeautomation)home-assistant/homeassistant/components/media_player/webostv.py", line 33, in <module>: Invalid type comment: Dict[str, str] [invalid-type-comment]
(open-homeautomation)home-assistant/homeassistant/components/device_tracker/bbox.py", line 37, in __init__: Invalid type comment: List[Device] [invalid-type-comment]
(BernardFW)bernard/src/bernard/i18n/loaders.py", line 116, in __init__: Invalid type comment: List[Callable[[TransDict]], None] [invalid-type-comment]
(BernardFW)bernard/src/bernard/i18n/loaders.py", line 198, in __init__: Invalid type comment: List[Callable[[IntentDict]], None] [invalid-type-comment]
(bastings)neuralmonkey/neuralmonkey/tf_manager.py", line 192, in execute: Invalid type comment: Set[Any] [invalid-type-comment]
(bastings)neuralmonkey/neuralmonkey/logging.py", line 18, in Logging: Invalid type comment: List[str] [invalid-type-comment]
(bastings)neuralmonkey/neuralmonkey/logging.py", line 20, in Logging: Invalid type comment: List[str] [invalid-type-comment]
(bastings)neuralmonkey/neuralmonkey/processors/german.py", line 13, in <module>: Invalid type comment: Dict[str, Dict[str, str]] [invalid-type-comment]
(bastings)neuralmonkey/neuralmonkey/runners/label_runner.py", line 44, in __init__: Invalid type comment: Option[ExecutionResult] [invalid-type-comment]
(bastings)neuralmonkey/neuralmonkey/runners/word_alignment_runner.py", line 41, in __init__: Invalid type comment: Optional[ExecutionResult] [invalid-type-comment]
(b-mueller)mythril/mythril/support/signatures.py", line 48, in Singleton: Invalid type comment: Dict[Singleton, Singleton] [invalid-type-comment]
(miniworld-project)miniworld_core/tests/acceptance/test_examples.py", line 26, in test_snapshot_boot_single_scenario: Invalid type comment: Dict [invalid-type-comment]
(miniworld-project)miniworld_core/tests/acceptance/test_examples.py", line 36, in test_snapshot_boot_multiple_scenarios: Invalid type comment: Dict [invalid-type-comment]
(miniworld-project)miniworld_core/tests/acceptance/test_examples.py", line 42, in test_snapshot_boot_multiple_scenarios: Invalid type comment: Dict [invalid-type-comment]
(miniworld-project)miniworld_core/tests/acceptance/test_examples.py", line 48, in test_snapshot_boot_multiple_scenarios: Invalid type comment: Dict [invalid-type-comment]
(Vadman97)PicoSim/hardware_sim/seven_segment_display.py", line 12, in __init__: Invalid type comment: Dict[str: bool] [invalid-type-comment]
(Vadman97)PicoSim/ops/assembler.py", line 105, in __init__: Invalid type comment: Dict[str, hex] [invalid-type-comment]
(Vadman97)PicoSim/ops/assembler.py", line 107, in __init__: Invalid type comment: Dict[str, hex] [invalid-type-comment]
(aio-libs)aiohttp/aiohttp/locks.py", line 22, in __init__: Invalid type comment: Deque[asyncio.Future[Any]] [invalid-type-comment]
(szeged)servo/tests/wpt/web-platform-tests/tools/wpt/utils.py", line 22, in Kwargs: Invalid type comment: (Kwargs) -> bool [invalid-type-comment]
(snakeleon)YouCompleteMe-x64/third_party/ycmd/third_party/jedi_deps/jedi/test/completion/pep0484_comments.py", line 5, in <module>: Invalid type comment: str but I write more [invalid-type-comment]
(juanjux)neme/src/core/python/backend.py", line 51, in __init__: Invalid type comment: List[Selection] [invalid-type-comment]
(DamnWidget)anaconda_go/lib/detector.py", line 22, in __init__: Invalid type comment: Union[str, List[str]] [invalid-type-comment]
(snapcore)snapcraft/snapcraft/project/errors.py", line 150, in _determine_cause: Invalid type comment: Dict[str, str] [invalid-type-comment]
(snapcore)snapcraft/snapcraft/project/errors.py", line 160, in _determine_cause: Invalid type comment: List[str] [invalid-type-comment]
(pckv)pcbot/plugins/music.py", line 39, in <module>: Invalid type comment: Dict[discord.Server, VoiceState] [invalid-type-comment]
(Microsoft)PTVS/Python/Product/Miniconda/Miniconda3-x64/Lib/site-packages/ruamel_yaml/error.py", line 114, in __str__: Invalid type comment: List[str] [invalid-type-comment]
(Microsoft)PTVS/Python/Product/Miniconda/Miniconda3-x64/Lib/site-packages/ruamel_yaml/error.py", line 154, in __str__: Invalid type comment: List[str] [invalid-type-comment]
(Microsoft)PTVS/Python/Product/Miniconda/Miniconda3-x64/Lib/site-packages/ruamel_yaml/error.py", line 241, in __str__: Invalid type comment: List[str] [invalid-type-comment]
(Microsoft)PTVS/Python/Product/Miniconda/Miniconda3-x64/Lib/site-packages/ruamel_yaml/reader.py", line 80, in __init__: Invalid type comment: Any [invalid-type-comment]
(Microsoft)PTVS/Python/Product/Miniconda/Miniconda3-x64/Lib/site-packages/ruamel_yaml/reader.py", line 84, in reset_reader: Invalid type comment: Any [invalid-type-comment]
(Microsoft)PTVS/Python/Product/Miniconda/Miniconda3-x64/Lib/site-packages/ruamel_yaml/reader.py", line 89, in reset_reader: Invalid type comment: Any [invalid-type-comment]
(Microsoft)PTVS/Python/Product/Miniconda/Miniconda3-x64/Lib/site-packages/ruamel_yaml/reader.py", line 91, in reset_reader: Invalid type comment: Union[None, Text] [invalid-type-comment]
(Microsoft)PTVS/Python/Product/Miniconda/Miniconda3-x64/Lib/site-packages/ruamel_yaml/timestamp.py", line 15, in __init__: Invalid type comment: Dict[Any, Any] [invalid-type-comment]
(Microsoft)PTVS/Python/Product/Miniconda/Miniconda3-x64/Lib/site-packages/ruamel_yaml/composer.py", line 35, in __init__: Invalid type comment: Dict[Any, Any] [invalid-type-comment]
(Microsoft)PTVS/Python/Product/Miniconda/Miniconda3-x64/Lib/site-packages/ruamel_yaml/composer.py", line 73, in get_single_node: Invalid type comment: Any [invalid-type-comment]
(Microsoft)PTVS/Python/Product/Miniconda/Miniconda3-x64/Lib/site-packages/ruamel_yaml/scalarstring.py", line 72, in walk_tree: Invalid type comment: Text [invalid-type-comment]
(Microsoft)PTVS/Python/Product/Miniconda/Miniconda3-x64/Lib/site-packages/ruamel_yaml/serializer.py", line 49, in __init__: Invalid type comment: Dict[Any, Any] [invalid-type-comment]
(Microsoft)PTVS/Python/Product/Miniconda/Miniconda3-x64/Lib/site-packages/ruamel_yaml/serializer.py", line 50, in __init__: Invalid type comment: Dict[Any, Any] [invalid-type-comment]
(Microsoft)PTVS/Python/Product/Miniconda/Miniconda3-x64/Lib/site-packages/ruamel_yaml/serializer.py", line 52, in __init__: Invalid type comment: Union[None, bool] [invalid-type-comment]
(Microsoft)PTVS/Python/Product/PythonTools/missing_req_packages.py", line 41, in <module>: Invalid type comment: List[Tuple[bytes, Text]] [invalid-type-comment]
(rr-)szurubooru/server/szurubooru/model/post.py", line 26, in PostFeature: Invalid type comment: Post [invalid-type-comment]
(jopohl)urh/src/urh/models/ProtocolTableModel.py", line 17, in __init__: Invalid type comment: urh.controller.CompareFrameController.CompareFrameController [invalid-type-comment]
(jopohl)urh/src/urh/models/SimulatorMessageFieldModel.py", line 21, in __init__: Invalid type comment: SimulatorTabController [invalid-type-comment]
(jopohl)urh/src/urh/signalprocessing/ChecksumLabel.py", line 25, in __init__: Invalid type comment: list[list[int,int]] [invalid-type-comment]
(jopohl)urh/src/urh/ui/views/TableView.py", line 14, in __init__: Invalid type comment: QPoint [invalid-type-comment]
(jopohl)urh/src/urh/ui/views/TextEditProtocolView.py", line 15, in __init__: Invalid type comment: list[Participant] [invalid-type-comment]
(jopohl)urh/src/urh/ui/views/TextEditProtocolView.py", line 16, in __init__: Invalid type comment: list[Message] [invalid-type-comment]
(jopohl)urh/src/urh/ui/views/ZoomableGraphicView.py", line 20, in __init__: Invalid type comment: QPoint [invalid-type-comment]
(jopohl)urh/src/urh/ui/views/ZoomAndDropableGraphicView.py", line 14, in __init__: Invalid type comment: ProtocolTreeItem [invalid-type-comment]
(jopohl)urh/tests/awre/TestAWREHistograms.py", line 126, in get_bitvectors_by_participant: Invalid type comment: Message [invalid-type-comment]
(DXsmiley)mathbot/mathbot/wolfapi.py", line 270, in __init__: Invalid type comment: typing.List[typing.Optional[PIL.Image]] [invalid-type-comment]
(ANR-COMPASS)shesha/shesha/widgets/widget_base.py", line 62, in __init__: Invalid type comment: Threading.Lock [invalid-type-comment]
(jessepeterson)commandment/commandment/dbtypes.py", line 82, in SetOfEnumValues: Invalid type comment: (List[Enum], any) -> str [invalid-type-comment]
(sourcegraph)srclib-python/grapher/structures.py", line 245, in fromJSONable: Invalid type comment: ignore (List.__parameters_ exists) [invalid-type-comment]
(sourcegraph)srclib-python/grapher/structures.py", line 245, in <listcomp>: Invalid type comment: ignore (List.__parameters_ exists) [invalid-type-comment]
(sourcegraph)srclib-python/grapher/structures.py", line 255, in fromJSONable: Invalid type comment: ignore (Dict.__parameters_ exists) [invalid-type-comment]
(sourcegraph)srclib-python/grapher/structures.py", line 274, in fromJSONable: Invalid type comment: ignore (SomeClass.__init__ exists) [invalid-type-comment]
(sourcegraph)srclib-python/grapher/builtin.py", line 1, in <module>: Invalid type comment: ignore (ignore strange redefinition of glob mypy error) [invalid-type-comment]
(RoboJackets)robocup-software/soccer/gameplay/fs_watcher.py", line 54, in _notify: Invalid type comment: List[str] [invalid-type-comment]
(barry-scott)scm-workbench/Source/Scm/wb_scm_app.py", line 36, in __init__: Invalid type comment: Dict[str, None] [invalid-type-comment]
(barry-scott)scm-workbench/Source/Common/wb_preferences.py", line 77, in __init__: Invalid type comment: Dict[str, Favorite] [invalid-type-comment]
(barry-scott)scm-workbench/Source/Common/wb_preferences.py", line 79, in __init__: Invalid type comment: Dict[str, Project] [invalid-type-comment]
(barry-scott)scm-workbench/Source/Common/wb_preferences.py", line 181, in __init__: Invalid type comment: Dict[str, Colour] [invalid-type-comment]
(barry-scott)scm-workbench/Source/Common/wb_tracked_qwidget.py", line 22, in WbTrackedModeless: Invalid type comment: Dict[int, WbTrackedModeless] [invalid-type-comment]
(irmen)Tale/tale/pubsub.py", line 42, in <module>: Invalid type comment: Dict[TopicNameType, Topic] [invalid-type-comment]
(vertexproject)synapse/synapse/lib/module.py", line 12, in __init__: Invalid type comment: synapse.cortex.Cortex [invalid-type-comment]
(vertexproject)synapse/synapse/lib/module.py", line 13, in __init__: Invalid type comment: synapse.datamodel.Model [invalid-type-comment]
(vertexproject)synapse/synapse/tests/test_model_crypto.py", line 38, in test_norm_lm_ntlm: Invalid type comment: s_cortex.Cortex [invalid-type-comment]
(vertexproject)synapse/synapse/tests/test_model_crypto.py", line 52, in test_forms_crypto_simple: Invalid type comment: s_cortex.Cortex [invalid-type-comment]
(vertexproject)synapse/synapse/tests/test_model_crypto.py", line 85, in test_form_rsakey: Invalid type comment: s_cortex.Cortex [invalid-type-comment]
(Brutus5000)BiReUS/tests/mocks/mock_download_service.py", line 22, in __init__: Invalid type comment: List[str] [invalid-type-comment]
(evernym)plenum/plenum/server/blacklister.py", line 19, in __init__: Invalid type comment: Set[str] [invalid-type-comment]
(evernym)plenum/plenum/server/req_authenticator.py", line 19, in __init__: Invalid type comment: Dict[str, Dict[str, List[str]]] [invalid-type-comment]
(evernym)plenum/plenum/server/replicas.py", line 31, in __init__: Invalid type comment: Dict[deque] [invalid-type-comment]
(evernym)plenum/plenum/recorder/replayable_node.py", line 17, in __init__: Invalid type comment: Dict[(int, int), List] [invalid-type-comment]
(evernym)plenum/plenum/test/monitoring/test_avg_latency.py", line 27, in testAvgReqLatency: Invalid type comment: Node [invalid-type-comment]
(evernym)plenum/plenum/common/transaction_store.py", line 42, in reset: Invalid type comment: Dict[str, Dict[int, str]] [invalid-type-comment]
(evernym)plenum/plenum/common/transaction_store.py", line 46, in reset: Invalid type comment: Dict[str, asyncio.Queue] [invalid-type-comment]
(evernym)plenum/plenum/common/transaction_store.py", line 50, in reset: Invalid type comment: Dict[str, Reply] [invalid-type-comment]
(evernym)plenum/plenum/common/latency_measurements.py", line 22, in __init__: Invalid type comment: Dict[str, (int, float)] [invalid-type-comment]
(evernym)plenum/stp_core/loop/looper.py", line 107, in __init__: Invalid type comment: Task [invalid-type-comment]
(evernym)plenum/stp_core/network/keep_in_touch.py", line 18, in __init__: Invalid type comment: Dict[int, Tuple[int, float]] [invalid-type-comment]
(box)ClusterRunner/app/master/slave.py", line 268, in __init__: Invalid type comment: Dict[str, Slave] [invalid-type-comment]
(box)ClusterRunner/app/master/slave.py", line 269, in __init__: Invalid type comment: Dict[str, Slave] [invalid-type-comment]
(NLHEALTHCARE)PYELT/pyelt/datalayers/sor.py", line 49, in reflect_2: Invalid type comment: List[Column] [invalid-type-comment]
(NLHEALTHCARE)PYELT/pyelt/helpers/pyelt_logging.py", line 42, in __init__: Invalid type comment: logging.logger [invalid-type-comment]
(NLHEALTHCARE)PYELT/pyelt/helpers/pyelt_logging.py", line 43, in __init__: Invalid type comment: datetime.datetime [invalid-type-comment]
(NLHEALTHCARE)PYELT/pyelt/helpers/pyelt_logging.py", line 44, in __init__: Invalid type comment: datetime.datetime [invalid-type-comment]
(NLHEALTHCARE)PYELT/pyelt/helpers/pyelt_logging.py", line 45, in __init__: Invalid type comment: List[str] [invalid-type-comment]
(NLHEALTHCARE)PYELT/pyelt/orm/dv_objects.py", line 68, in __init__: Invalid type comment: Dict[int, Row] [invalid-type-comment]
(NLHEALTHCARE)PYELT/pyelt/mappings/transformations.py", line 21, in __init__: Invalid type comment: Dict[int, FieldTransformStep] [invalid-type-comment]
(vakabus)pybakalib/pybakalib/modules/marks.py", line 53, in __init__: Invalid type comment: List[Mark] [invalid-type-comment]
(jesopo)bitbot/src/IRCBot.py", line 44, in __init__: Invalid type comment: typing.Queue[TriggerEvent] [invalid-type-comment]
(MartinHjelmare)home-assistant/homeassistant/util/yaml.py", line 25, in <module>: Invalid type comment: Dict[str, JSON_TYPE] [invalid-type-comment]
(SunDwarf)Kyoukai/kyoukai/route.py", line 50, in __init__: Invalid type comment: Blueprint [invalid-type-comment]
(alephobjects)Cura2/cura/PreviewPass.py", line 28, in __init__: Invalid type comment: Optional[Camera] [invalid-type-comment]
(alephobjects)Cura2/cura/LayerPolygon.py", line 221, in LayerPolygon: Invalid type comment: numpy.ndarray[Any] [invalid-type-comment]
(will7200)Yugioh-bot/bot/modes/Battle.py", line 29, in __init__: Invalid type comment: Provider [invalid-type-comment]
(will7200)Yugioh-bot/bot/modes/SpecialEvents.py", line 19, in __init__: Invalid type comment: Provider [invalid-type-comment]
(manu0466)BookingBot/src/booking/scheduler/Scheduler.py", line 42, in __init__: Invalid type comment: List[BaseSpider] [invalid-type-comment]
(anokata)pythonPetProjects/mytest.py", line 4, in <module>: Invalid type comment: (int) -> int [invalid-type-comment]
(anokata)pythonPetProjects/mytest.py", line 10, in <module>: Invalid type comment: (str) -> int [invalid-type-comment]
(5nizza)party-elli/automata/aht2dot.py", line 26, in convert: Invalid type comment: Set['InvNode'] [invalid-type-comment]
(the-virtual-brain)tvb-hpc/tvb_hpc/rng.py", line 66, in __init__: Invalid type comment: Compiler [invalid-type-comment]
(missionpinball)mpf/mpf/devices/autofire.py", line 52, in __init__: Invalid type comment: List[float] [invalid-type-comment]
(missionpinball)mpf/mpf/devices/digital_output.py", line 33, in __init__: Invalid type comment: Union[DriverPlatformInterface, LightPlatformInterface] [invalid-type-comment]
(missionpinball)mpf/mpf/devices/digital_output.py", line 34, in __init__: Invalid type comment: Union[DriverPlatform, LightsPlatform] [invalid-type-comment]
(missionpinball)mpf/mpf/devices/ball_save.py", line 33, in __init__: Invalid type comment: Playfield [invalid-type-comment]
(missionpinball)mpf/mpf/devices/achievement_group.py", line 35, in __init__: Invalid type comment: RunningShow [invalid-type-comment]
(missionpinball)mpf/mpf/devices/achievement_group.py", line 38, in __init__: Invalid type comment: Achievement [invalid-type-comment]
(missionpinball)mpf/mpf/devices/switch.py", line 32, in __init__: Invalid type comment: SwitchPlatformInterface [invalid-type-comment]
(missionpinball)mpf/mpf/devices/switch.py", line 33, in __init__: Invalid type comment: SwitchPlatform [invalid-type-comment]
(missionpinball)mpf/mpf/devices/segment_display.py", line 30, in __init__: Invalid type comment: SegmentDisplayPlatformInterface [invalid-type-comment]
(missionpinball)mpf/mpf/devices/ball_device/physical_ball_counter.py", line 29, in __init__: Invalid type comment: BallCountHandler [invalid-type-comment]
(missionpinball)mpf/mpf/devices/ball_device/physical_ball_counter.py", line 196, in __init__: Invalid type comment: BallDevice [invalid-type-comment]
(missionpinball)mpf/mpf/devices/ball_device/physical_ball_counter.py", line 198, in __init__: Invalid type comment: MachineController [invalid-type-comment]
(missionpinball)mpf/mpf/config_players/segment_display_player.py", line 30, in play: Invalid type comment: Dict[str, SegmentDisplay] [invalid-type-comment]
(missionpinball)mpf/mpf/config_players/hardware_sound_player.py", line 25, in play: Invalid type comment: HardwareSoundSystem [invalid-type-comment]
(missionpinball)mpf/mpf/platforms/base_serial_communicator.py", line 35, in __init__: Invalid type comment: Generator[int, None, None] [invalid-type-comment]
(missionpinball)mpf/mpf/core/device.py", line 45, in __init__: Invalid type comment: SmartVirtualHardwarePlatform [invalid-type-comment]
(missionpinball)mpf/mpf/core/file_interface.py", line 14, in FileInterface: Invalid type comment: List[str] [invalid-type-comment]
(missionpinball)mpf/mpf/core/logging.py", line 22, in __init__: Invalid type comment: Logger [invalid-type-comment]
(missionpinball)mpf/mpf/core/file_manager.py", line 17, in FileManager: Invalid type comment: Dict[str, YamlInterface] [invalid-type-comment]
(missionpinball)mpf/mpf/core/device_manager.py", line 71, in _load_device_config_spec: Invalid type comment: Device [invalid-type-comment]
(missionpinball)mpf/mpf/core/device_manager.py", line 84, in _load_device_modules: Invalid type comment: Device [invalid-type-comment]
(missionpinball)mpf/mpf/core/bcp/bcp_transport.py", line 21, in __init__: Invalid type comment: MachineController [invalid-type-comment]
(missionpinball)mpf/mpf/plugins/auditor.py", line 36, in __init__: Invalid type comment: Set[str] [invalid-type-comment]
(missionpinball)mpf/mpf/plugins/auditor.py", line 37, in __init__: Invalid type comment: Any [invalid-type-comment]
(missionpinball)mpf/mpf/plugins/auditor.py", line 38, in __init__: Invalid type comment: Any [invalid-type-comment]
(kidosoft)Morelia/morelia/grammar.py", line 48, in Node: Invalid type comment: Iterable[Type[Node]] [invalid-type-comment]
(jbms)beancount-import/beancount_import/source/__init__.py", line 123, in __init__: Invalid type comment: Set[str] [invalid-type-comment]
(jbms)beancount-import/beancount_import/source/__init__.py", line 126, in __init__: Invalid type comment: Set[Tuple[str, str, FrozenSet[Tuple[str, Any]]]] [invalid-type-comment]
(dbrattli)aioreactive/test/test_map.py", line 20, in test_map_happy: Invalid type comment: AsyncObservable[int] [invalid-type-comment]
(Enether)python_wow/zones/zone.py", line 10, in Zone: Invalid type comment: dict - key: current_subzone: str, value: A list of subzones: str which we can go to [invalid-type-comment]
(bitmovin)bitmovin-python/tests/bitmovin/services/manifests/hls/hls_manifest_tests.py", line 24, in setUp: Invalid type comment: Encoding [invalid-type-comment]
(bitmovin)bitmovin-python/tests/bitmovin/services/manifests/dash/dash_manifest_tests.py", line 25, in setUp: Invalid type comment: Encoding [invalid-type-comment]
(bitmovin)bitmovin-python/tests/bitmovin/services/manifests/smooth/smooth_manifest_tests.py", line 24, in setUp: Invalid type comment: Encoding [invalid-type-comment]
(caterinaurban)Typpete/typpete/src/stubs/libraries/csv.py", line 7, in Dialect: Invalid type comment: Optional[str] [invalid-type-comment]
(caterinaurban)Typpete/typpete/src/stubs/libraries/csv.py", line 8, in Dialect: Invalid type comment: Optional[str] [invalid-type-comment]
(FrodeSolheim)fs-uae-launcher/fsbc/signal.py", line 69, in Signal: Invalid type comment: Signal [invalid-type-comment]
(FrodeSolheim)fs-uae-launcher/arcade/glui/texturemanager.py", line 13, in TextureManager: Invalid type comment: TextureManager [invalid-type-comment]
(AbeelLab)phasm/phasm/io/gfa.py", line 174, in gfa2_reconstruct_assembly_graph: Invalid type comment: Mapping[str, Node] [invalid-type-comment]
(AbeelLab)phasm/phasm/io/sequences.py", line 23, in __init__: Invalid type comment: Mapping[OrientedDNASegment, bytes] [invalid-type-comment]
(saltyrtc)saltyrtc-server-python/saltyrtc/server/util.py", line 54, in <module>: Invalid type comment: Optional[logbook.compat.RedirectLoggingHandler] [invalid-type-comment]
(saltyrtc)saltyrtc-server-python/saltyrtc/server/util.py", line 55, in <module>: Invalid type comment: Optional[logbook.compat.LoggingHandler] [invalid-type-comment]
(saltyrtc)saltyrtc-server-python/tests/test_common.py", line 193, in TestSubprotocol: Invalid type comment: List[any] [invalid-type-comment]
(space-wizards)space-station-14/Tools/package_release_build.py", line 100, in <module>: Invalid type comment: (bool) -> None [invalid-type-comment]
(space-wizards)space-station-14/Tools/package_release_build.py", line 150, in <module>: Invalid type comment: (bool) -> None [invalid-type-comment]
(space-wizards)space-station-14/Tools/package_release_build.py", line 202, in <module>: Invalid type comment: (bool) -> None [invalid-type-comment]
(polygraph-python)polygraph/polygraph/types.py", line 66, in PolygraphValue: Invalid type comment: Object [invalid-type-comment]
(mittagessen)kraken/kraken/lib/dataset.py", line 275, in __init__: Invalid type comment: Union[List[Image], List[torch.Tensor]] [invalid-type-comment]
(mittagessen)kraken/kraken/lib/dataset.py", line 345, in encode: Invalid type comment: List[Tuple[Union[Image, torch.Tensor], torch.Tensor]] [invalid-type-comment]
(kolypto)py-mongosql/mongosql/util/history_proxy.py", line 66, in __copy_from_instance: Invalid type comment: AttributeState [invalid-type-comment]
(DatapuntAmsterdam)handelsregister/web/handelsregister/search/views.py", line 149, in autocomplete_queries: Invalid type comment: ElasticQueryWrapper [invalid-type-comment]
(foursquare)fsqio/src/python/fsqio/pants/python/tasks/mypy_task.py", line 65, in _calculate_python_sources: Invalid type comment: Set[str] [invalid-type-comment]
(foursquare)fsqio/src/python/fsqio/pants/python/examples/type_hints_cheat_sheet.py", line 32, in <module>: Invalid type comment: (int, int) -> int [invalid-type-comment]
(ajbouh)tfi/src/tfi/parse/iterators.py", line 52, in __init__: Invalid type comment: Iterable [invalid-type-comment]
(catb0t)mouse16/mouseStack.py", line 115, in popn: Invalid type comment: List[Any] [invalid-type-comment]
(catb0t)mouse16/mouseStack.py", line 474, in put: Invalid type comment: Union[Any, Any] [invalid-type-comment]
(catb0t)mouse16/mouseStack.py", line 486, in emit: Invalid type comment: Union[str, int] [invalid-type-comment]
(pgjones)flake8-sql/flake8_sql/parser.py", line 64, in __init__: Invalid type comment: Tuple[sqlparse.sql.Token, int] [invalid-type-comment]
(drhagen)parsita/src/parsita/state.py", line 24, in Reader: Invalid type comment: Reader[Input] [invalid-type-comment]
(timabbott)zulip/scripts/setup/generate_secrets.py", line 72, in generate_secrets: Invalid type comment: List[str] [invalid-type-comment]
(timabbott)zulip/scripts/lib/setup_venv.py", line 181, in try_to_copy_venv: Invalid type comment: List[Tuple[int, str, Set[str]]] [invalid-type-comment]
(timabbott)zulip/scripts/lib/setup_venv.py", line 182, in try_to_copy_venv: Invalid type comment: Set[str] [invalid-type-comment]
(timabbott)zulip/scripts/lib/hash_reqs.py", line 19, in expand_reqs_helper: Invalid type comment: List[str] [invalid-type-comment]
(timabbott)zulip/tools/zulint/lister.py", line 82, in list_files: Invalid type comment: Dict[str, List[str]] [invalid-type-comment]
(timabbott)zulip/tools/zulint/lister.py", line 83, in list_files: Invalid type comment: List[str] [invalid-type-comment]
(timabbott)zulip/tools/zulint/command.py", line 52, in LinterConfig: Invalid type comment: Dict[str, Callable[[], int]] [invalid-type-comment]
(timabbott)zulip/tools/zulint/command.py", line 76, in run_linter: Invalid type comment: List[str] [invalid-type-comment]
(timabbott)zulip/zerver/tornado/descriptors.py", line 6, in <module>: Invalid type comment: Dict[int, ClientDescriptor] [invalid-type-comment]
(ingokegel)intellij-community/python/testData/intentions/PyAnnotateVariableTypeIntentionTest/notSuggestedForLocalAssignmentTargetWithUnresolvedTypeComment.py", line 2, in func: Invalid type comment: Any [invalid-type-comment]
(ingokegel)intellij-community/python/testData/inspections/AddClassFromTypeComment.py", line 2, in f: Invalid type comment: <warning descr="Unresolved reference 'MyClass'">My<caret>Class</warning> [invalid-type-comment]
(ingokegel)intellij-community/python/testData/quickFixes/PyTypeHintsQuickFixTest/parenthesesAndCustomTarget.py", line 9, in <module>: Invalid type comment: <warning descr="Generics should be specified through square brackets">A<caret>(int)</warning> [invalid-type-comment]
(ingokegel)intellij-community/python/testData/quickFixes/PyTypeHintsQuickFixTest/selfInTypeComment.py", line 3, in method: Invalid type comment: <error descr="Invalid type 'self'">se<caret>lf</error>.B [invalid-type-comment]
(ingokegel)intellij-community/python/testData/quickFixes/PyTypeHintsQuickFixTest/selfInTypeComment_after.py", line 3, in method: Invalid type comment: A.B [invalid-type-comment]
(aclowes)yawn/yawn/worker/executor.py", line 51, in __init__: Invalid type comment: typing.Dict[typing.io, Execution] [invalid-type-comment]
(angr)angr/tests/test_types.py", line 155, in test_top_type: Invalid type comment: Dict[str, SimTypeFunction] [invalid-type-comment]
(angr)angr/tests/test_types.py", line 163, in test_arg_names: Invalid type comment: Dict[str, SimTypeFunction] [invalid-type-comment]
(angr)angr/tests/test_types.py", line 169, in test_arg_names: Invalid type comment: Dict[str, SimTypeFunction] [invalid-type-comment]
(angr)angr/tests/test_types.py", line 173, in test_arg_names: Invalid type comment: Dict[str, SimTypeFunction] [invalid-type-comment]
(qutebrowser)qutebrowser/qutebrowser/extensions/loader.py", line 54, in InitContext: Invalid type comment: argparse.Namespace [invalid-type-comment]
(qutebrowser)qutebrowser/qutebrowser/misc/objects.py", line 41, in <module>: Invalid type comment: typing.Union[usertypes.Backend, NoBackend] [invalid-type-comment]
(qutebrowser)qutebrowser/qutebrowser/misc/objects.py", line 42, in <module>: Invalid type comment: typing.Dict[str, command.Command] [invalid-type-comment]
(RudolfCardinal)crate/crate_anon/nlp_webserver/tasks.py", line 273, in process_nlp_text: Invalid type comment: Optional[DocProcRequest] [invalid-type-comment]
(msincenselee)vnpy/vnpy/api/websocket/WebsocketClient.py", line 91, in WebsocketClient: Invalid type comment: (dict)->None [invalid-type-comment]
(msincenselee)vnpy/vnpy/api/websocket/WebsocketClient.py", line 98, in WebsocketClient: Invalid type comment: (str)->None [invalid-type-comment]
(msincenselee)vnpy/vnpy/api/websocket/WebsocketClient.py", line 103, in WebsocketClient: Invalid type comment: (bytes)->None [invalid-type-comment]
(msincenselee)vnpy/vnpy/api/rest/RestClient.py", line 177, in RestClient: Invalid type comment: (Request)->Request [invalid-type-comment]
(msincenselee)vnpy/vnpy/api/rest/RestClient.py", line 187, in RestClient: Invalid type comment: (int, Request)->None [invalid-type-comment]
(msincenselee)vnpy/vnpy/api/rest/RestClient.py", line 234, in RestClient: Invalid type comment: (Request, requests.Session)->None [invalid-type-comment]
(Chandlercjy)OnePy/OnePy/environment.py", line 122, in clear_modules: Invalid type comment: List[Dict] [invalid-type-comment]
(Ultimaker)Cura/cura/PreviewPass.py", line 45, in __init__: Invalid type comment: Optional[Camera] [invalid-type-comment]
(Ultimaker)Cura/cura/LayerPolygon.py", line 229, in LayerPolygon: Invalid type comment: numpy.ndarray[Any] [invalid-type-comment]
(Ultimaker)Cura/cura/PrinterOutput/PrinterOutputDevice.py", line 75, in __init__: Invalid type comment: List[PrinterOutputModel] [invalid-type-comment]
(Ultimaker)Cura/cura/PrinterOutput/PrinterOutputDevice.py", line 76, in __init__: Invalid type comment: List[PrinterConfigurationModel] [invalid-type-comment]
(Ultimaker)Cura/cura/PrinterOutput/PrinterOutputDevice.py", line 96, in __init__: Invalid type comment: Optional[FirmwareUpdater] [invalid-type-comment]
(Ultimaker)Cura/cura/PrinterOutput/Models/PrinterConfigurationModel.py", line 19, in __init__: Invalid type comment: List[ExtruderConfigurationModel] [invalid-type-comment]
(Ultimaker)Cura/plugins/FirmwareUpdater/FirmwareUpdaterMachineAction.py", line 29, in __init__: Invalid type comment: Optional[PrinterOutputDevice] [invalid-type-comment]
(Ultimaker)Cura/plugins/FirmwareUpdater/FirmwareUpdaterMachineAction.py", line 30, in __init__: Invalid type comment: Optional[FirmwareUpdater] [invalid-type-comment]
(NZSmartie)PyHIDParser/hidparser/Physical.py", line 134, in __init__: Invalid type comment: Dict[int, PhysicalDescriptorSubSet] [invalid-type-comment]
(tensorflow)models/official/utils/logs/mlperf_helper.py", line 64, in <module>: Invalid type comment: (str) -> typing.Optional[ParsedLine] [invalid-type-comment]
(tensorflow)models/official/utils/logs/mlperf_helper.py", line 77, in <module>: Invalid type comment: (ParsedLine) -> str [invalid-type-comment]
(tensorflow)models/official/recommendation/stat_utils.py", line 61, in <module>: Invalid type comment: (np.ndarray, int) -> np.ndarray [invalid-type-comment]
(Shopify)shopify_python/shopify_python/__init__.py", line 13, in <module>: Invalid type comment: (lint.PyLinter) -> None [invalid-type-comment]
(Shopify)shopify_python/shopify_python/ast.py", line 4, in <module>: Invalid type comment: (astroid.NodeNG) -> int [invalid-type-comment]
(Shopify)shopify_python/shopify_python/shopify_styleguide.py", line 12, in <module>: Invalid type comment: (lint.PyLinter) -> None [invalid-type-comment]
(terrencepreilly)darglint/darglint/error_report.py", line 73, in ErrorReport: Invalid type comment: (DarglintError) -> str [invalid-type-comment]
(terrencepreilly)darglint/darglint/error_report.py", line 97, in ErrorReport: Invalid type comment: () -> str [invalid-type-comment]
(terrencepreilly)darglint/darglint/function_description.py", line 26, in <module>: Invalid type comment: (str) -> str [invalid-type-comment]
(terrencepreilly)darglint/darglint/function_description.py", line 127, in <module>: Invalid type comment: (Union[ast.FunctionDef, ast.AsyncFunctionDef]) -> bool [invalid-type-comment]
(terrencepreilly)darglint/darglint/function_description.py", line 134, in <module>: Invalid type comment: (ast.AST) -> str [invalid-type-comment]
(terrencepreilly)darglint/darglint/function_description.py", line 138, in <module>: Invalid type comment: (ast.AST) -> Iterator[Union[ast.FunctionDef, ast.AsyncFunctionDef]] [invalid-type-comment]
(terrencepreilly)darglint/darglint/function_description.py", line 144, in <module>: Invalid type comment: (ast.AST) -> Iterator[ast.ClassDef] [invalid-type-comment]
(terrencepreilly)darglint/darglint/function_description.py", line 150, in <module>: Invalid type comment: (ast.AST) -> Iterator[Union[ast.FunctionDef, ast.AsyncFunctionDef]] [invalid-type-comment]
(terrencepreilly)darglint/darglint/function_description.py", line 156, in <module>: Invalid type comment: (Union[ast.FunctionDef, ast.AsyncFunctionDef]) -> List[str] [invalid-type-comment]
(terrencepreilly)darglint/darglint/function_description.py", line 175, in <module>: Invalid type comment: (Union[ast.FunctionDef, ast.AsyncFunctionDef]) -> bool [invalid-type-comment]
(terrencepreilly)darglint/darglint/function_description.py", line 179, in <module>: Invalid type comment: (Union[ast.FunctionDef, ast.AsyncFunctionDef]) -> bool [invalid-type-comment]
(terrencepreilly)darglint/darglint/function_description.py", line 202, in <module>: Invalid type comment: (ast.Raise) -> str [invalid-type-comment]
(terrencepreilly)darglint/darglint/function_description.py", line 222, in <module>: Invalid type comment: (Union[ast.FunctionDef, ast.AsyncFunctionDef]) -> Set[str] [invalid-type-comment]
(terrencepreilly)darglint/darglint/config.py", line 81, in <module>: Invalid type comment: (str) -> Configuration [invalid-type-comment]
(terrencepreilly)darglint/darglint/config.py", line 140, in <module>: Invalid type comment: () -> Iterable[str] [invalid-type-comment]
(terrencepreilly)darglint/darglint/config.py", line 161, in <module>: Invalid type comment: (str) -> Optional[str] [invalid-type-comment]
(terrencepreilly)darglint/darglint/config.py", line 188, in <module>: Invalid type comment: () -> Optional[str] [invalid-type-comment]
(terrencepreilly)darglint/darglint/config.py", line 204, in <module>: Invalid type comment: () -> Configuration [invalid-type-comment]
(terrencepreilly)darglint/darglint/config.py", line 223, in <module>: Invalid type comment: () -> Logger [invalid-type-comment]
(quantumlib)Cirq/cirq/protocols/circuit_diagram_info.py", line 84, in CircuitDiagramInfoArgs: Invalid type comment: CircuitDiagramInfoArgs [invalid-type-comment]
(quantumlib)Cirq/cirq/circuits/_block_diagram_drawer.py", line 162, in __init__: Invalid type comment: Dict[Tuple[int, int], Block] [invalid-type-comment]
(quantumlib)Cirq/cirq/circuits/_block_diagram_drawer.py", line 164, in __init__: Invalid type comment: Dict[int, int] [invalid-type-comment]
(quantumlib)Cirq/cirq/circuits/_block_diagram_drawer.py", line 166, in __init__: Invalid type comment: Dict[int, int] [invalid-type-comment]
(quantumlib)Cirq/cirq/circuits/insert_strategy.py", line 21, in InsertStrategy: Invalid type comment: InsertStrategy [invalid-type-comment]
(quantumlib)Cirq/cirq/circuits/insert_strategy.py", line 22, in InsertStrategy: Invalid type comment: InsertStrategy [invalid-type-comment]
(quantumlib)Cirq/cirq/circuits/insert_strategy.py", line 23, in InsertStrategy: Invalid type comment: InsertStrategy [invalid-type-comment]
(quantumlib)Cirq/cirq/circuits/insert_strategy.py", line 24, in InsertStrategy: Invalid type comment: InsertStrategy [invalid-type-comment]
(quantumlib)Cirq/cirq/google/sim/mem_manager.py", line 38, in SharedMemManager: Invalid type comment: SharedMemManager [invalid-type-comment]
(quantumlib)Cirq/cirq/ops/pauli_gates.py", line 30, in Pauli: Invalid type comment: Tuple[Pauli, Pauli, Pauli] [invalid-type-comment]
(quantumlib)Cirq/cirq/ops/qubit_order.py", line 44, in QubitOrder: Invalid type comment: QubitOrder [invalid-type-comment]
(quantumlib)Cirq/cirq/ops/pauli_interaction_gate.py", line 41, in PauliInteractionGate: Invalid type comment: PauliInteractionGate [invalid-type-comment]
(quantumlib)Cirq/cirq/ops/pauli_interaction_gate.py", line 42, in PauliInteractionGate: Invalid type comment: PauliInteractionGate [invalid-type-comment]
(FAForever)client/src/coop/_coopwidget.py", line 27, in __init__: Invalid type comment: ClientWindow [invalid-type-comment]
(FAForever)client/src/modvault/uploadwidget.py", line 20, in __init__: Invalid type comment: ClientWindow [invalid-type-comment]
(FAForever)client/src/fa/game_session.py", line 51, in __init__: Invalid type comment: GameProcess [invalid-type-comment]
(FAForever)client/src/fa/wizards.py", line 79, in __init__: Invalid type comment: ClientWindow [invalid-type-comment]
(FAForever)client/src/games/hostgamewidget.py", line 93, in __init__: Invalid type comment: ClientWindow [invalid-type-comment]
(FAForever)client/src/games/_gameswidget.py", line 37, in __init__: Invalid type comment: ClientWindow [invalid-type-comment]
(repleo)bounca/bounca/certificate_engine/ssl/certificate.py", line 27, in __init__: Invalid type comment: x509.Certificate [invalid-type-comment]
(repleo)bounca/bounca/certificate_engine/ssl/certificate.py", line 28, in __init__: Invalid type comment: x509.CertificateBuilder [invalid-type-comment]
(thorrak)fermentrack/utils/processmgr_class.py", line 48, in __init__: Invalid type comment: function [invalid-type-comment]
(RulersOfAsgard)ALAMO-worker/alamo_worker/plugins/__init__.py", line 192, in dispatch: Invalid type comment: List[AbstractResult] [invalid-type-comment]
(kimjinyong)i2nsf-framework/Hackathon-105/jetconf/jetconf/handler_list.py", line 116, in __init__: Invalid type comment: List[Tuple[HandlerSelectorT, BaseDataListener]] [invalid-type-comment]
(guardian)alerta/alerta/models/switch.py", line 20, in Switch: Invalid type comment: List[Switch] [invalid-type-comment]
(purduesigbots)pros-cli/pros/common/ui/interactive/observable.py", line 9, in <module>: Invalid type comment: Dict[str, Observable] [invalid-type-comment]
(oysstu)pyxtf/pyxtf/xtf_util.py", line 36, in plot_navigation: Invalid type comment: List[pyxtf.XTFHeaderNavigation] [invalid-type-comment]
(zhreshold)mxnet/tests/python-pytest/onnx/backend_test.py", line 35, in <module>: Invalid type comment: () -> unittest.TestSuite [invalid-type-comment]
(numberoverzero)bottom/bottom/protocol.py", line 15, in Protocol: Invalid type comment: RawClient [invalid-type-comment]
(geome-mitbbs)QTS_Research/IB_Api/ibapi/contract.py", line 28, in __init__: Invalid type comment: int; LegOpenClose enum values [invalid-type-comment]
(geome-mitbbs)QTS_Research/IB_Api/ibapi/contract.py", line 79, in __init__: Invalid type comment: str; received in open order 14 and up for all combos [invalid-type-comment]
(geome-mitbbs)QTS_Research/IB_Api/ibapi/contract.py", line 80, in __init__: Invalid type comment: list<ComboLeg> [invalid-type-comment]
(geome-mitbbs)QTS_Research/IB_Api/ibapi/contract.py", line 193, in __init__: Invalid type comment: list of strings [invalid-type-comment]
(geome-mitbbs)QTS_Research/IB_Api/ibapi/order.py", line 63, in __init__: Invalid type comment: float; REL orders only [invalid-type-comment]
(geome-mitbbs)QTS_Research/IB_Api/ibapi/order.py", line 66, in __init__: Invalid type comment: float; TRAILLIMIT orders only [invalid-type-comment]
(geome-mitbbs)QTS_Research/IB_Api/ibapi/order.py", line 78, in __init__: Invalid type comment: int; 1 if you hold the shares, 2 if they will be delivered from elsewhere.  Only for Action=SSHORT [invalid-type-comment]
(geome-mitbbs)QTS_Research/IB_Api/ibapi/order.py", line 89, in __init__: Invalid type comment: int; AUCTION_MATCH, AUCTION_IMPROVEMENT, AUCTION_TRANSPARENT [invalid-type-comment]
(geome-mitbbs)QTS_Research/IB_Api/ibapi/order.py", line 115, in __init__: Invalid type comment: int; 1=Average, 2 = BidOrAsk [invalid-type-comment]
(geome-mitbbs)QTS_Research/IB_Api/ibapi/order.py", line 118, in __init__: Invalid type comment: float; EFP orders only [invalid-type-comment]
(geome-mitbbs)QTS_Research/IB_Api/ibapi/order.py", line 119, in __init__: Invalid type comment: int;  EFP orders only [invalid-type-comment]
(Techcable)DiffUtils/diffutils/engine.py", line 52, in DiffEngine: Invalid type comment: DiffEngine [invalid-type-comment]
(snakeleon)YouCompleteMe-x86/third_party/ycmd/third_party/JediHTTP/vendor/jedi/test/completion/pep0484_comments.py", line 5, in <module>: Invalid type comment: str but I write more [invalid-type-comment]
(mrgambal)vulyk/vulyk/blueprints/__init__.py", line 20, in __init__: Invalid type comment: list[LambdaType[dict]] [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/__init__.py", line 21, in <module>: Invalid type comment: (Union[IO[bytes], Text]) -> bytes [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/__init__.py", line 32, in <module>: Invalid type comment: (bytes, Union[IO[bytes], Text]) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/__init__.py", line 40, in <module>: Invalid type comment: (Union[bytes, google.protobuf.message.Message]) -> bytes [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/__init__.py", line 63, in <module>: Invalid type comment: (bytes, _Proto) -> _Proto [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/__init__.py", line 89, in <module>: Invalid type comment: (Union[IO[bytes], Text], Optional[Any]) -> ModelProto [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/__init__.py", line 104, in <module>: Invalid type comment: (Union[IO[bytes], Text], Optional[Any]) -> TensorProto [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/__init__.py", line 119, in <module>: Invalid type comment: (bytes, Optional[Any]) -> ModelProto [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/__init__.py", line 133, in <module>: Invalid type comment: (bytes, Optional[Any]) -> TensorProto [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/__init__.py", line 147, in <module>: Invalid type comment: (Union[ModelProto, bytes], Union[IO[bytes], Text], Optional[Any]) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/__init__.py", line 160, in <module>: Invalid type comment: (TensorProto, Union[IO[bytes], Text]) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/defs/__init__.py", line 22, in <module>: Invalid type comment: () -> int [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/runner/__init__.py", line 34, in <module>: Invalid type comment: (int) -> Callable[[Callable[..., Any]], Callable[..., Any]] [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/runner/__init__.py", line 37, in retry_excute: Invalid type comment: (Callable[..., Any]) -> Callable[..., Any] [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/runner/__init__.py", line 54, in Runner: Invalid type comment: (Type[Backend], Optional[str]) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/runner/__init__.py", line 81, in Runner: Invalid type comment: (Text) -> Type[unittest.TestCase] [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/runner/__init__.py", line 87, in Runner: Invalid type comment: (Text) -> Runner [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/runner/__init__.py", line 91, in Runner: Invalid type comment: (Text) -> Runner [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/runner/__init__.py", line 95, in Runner: Invalid type comment: () -> Runner [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/runner/__init__.py", line 198, in Runner: Invalid type comment: (TestCase) -> Text [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/runner/__init__.py", line 230, in _add_test: Invalid type comment: (Text) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/runner/__init__.py", line 256, in Runner: Invalid type comment: (TestCase, Text) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/runner/__init__.py", line 261, in _add_model_test: Invalid type comment: (Any, Text) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/case/__init__.py", line 13, in <module>: Invalid type comment: () -> Dict[Text, List[Tuple[Text, Text]]] [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/case/node/__init__.py", line 20, in <module>: Invalid type comment: (np.ndarray, Text) -> onnx.ValueInfoProto [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/case/node/__init__.py", line 56, in <module>: Invalid type comment: () -> List[TestCase] [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/case/model/__init__.py", line 40, in <module>: Invalid type comment: () -> List[TestCase] [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/report/__init__.py", line 15, in <module>: Invalid type comment: (Any, Text) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/report/__init__.py", line 24, in <module>: Invalid type comment: (pytest.nodes.Item) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/report/__init__.py", line 31, in <module>: Invalid type comment: (Any) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/gen_proto.py", line 33, in <module>: Invalid type comment: (Iterable[Text], bool) -> Iterable[Text] [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/gen_proto.py", line 59, in <module>: Invalid type comment: (Iterable[Text], Text) -> Iterable[Text] [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/gen_proto.py", line 79, in <module>: Invalid type comment: (Iterable[Text]) -> Iterable[Text] [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/gen_proto.py", line 102, in <module>: Invalid type comment: (Text, int, bool, Text) -> Text [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/gen_proto.py", line 103, in translate: Invalid type comment: Iterable[Text] [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/gen_proto.py", line 113, in <module>: Invalid type comment: (Text, Text) -> Text [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/gen_proto.py", line 117, in <module>: Invalid type comment: (Text, Text, Text, bool) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/gen_proto.py", line 173, in <module>: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/checker.py", line 42, in <module>: Invalid type comment: (Type[Message]) -> Callable[[FuncType], FuncType] [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/checker.py", line 43, in _create_checker: Invalid type comment: (FuncType) -> FuncType [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/checker.py", line 45, in decorator: Invalid type comment: (Message, C.CheckerContext) -> Any [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/checker.py", line 57, in <module>: Invalid type comment: (ValueInfoProto, C.CheckerContext) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/checker.py", line 62, in <module>: Invalid type comment: (TensorProto, C.CheckerContext) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/checker.py", line 67, in <module>: Invalid type comment: (AttributeProto, C.CheckerContext) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/checker.py", line 72, in <module>: Invalid type comment: (NodeProto, C.CheckerContext) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/checker.py", line 77, in <module>: Invalid type comment: (GraphProto, C.CheckerContext) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/checker.py", line 81, in <module>: Invalid type comment: (ModelProto) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/version_converter.py", line 33, in <module>: Invalid type comment: (ModelProto, int) -> ModelProto [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/numpy_helper.py", line 20, in <module>: Invalid type comment: (Sequence[int]) -> Sequence[np.complex64] [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/numpy_helper.py", line 24, in <module>: Invalid type comment: (TensorProto) -> np.ndarray[Any] [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/numpy_helper.py", line 66, in <module>: Invalid type comment: (np.ndarray[Any], Optional[Text]) -> TensorProto [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/shape_inference.py", line 30, in <module>: Invalid type comment: (ModelProto) -> ModelProto [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/optimizer.py", line 41, in <module>: Invalid type comment: (ModelProto, Sequence[Text]) -> ModelProto [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/defs/gen_shape_inference_information.py", line 9, in <module>: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/stat_coverage.py", line 14, in <module>: Invalid type comment: (Sequence[defs.OpSchema]) -> bool [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/stat_coverage.py", line 21, in <module>: Invalid type comment: (IO[Any], bool) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/cmd_tools.py", line 21, in <module>: Invalid type comment: (argparse.Namespace) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/cmd_tools.py", line 23, in generate_data: Invalid type comment: (Text) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/cmd_tools.py", line 60, in <module>: Invalid type comment: () -> argparse.Namespace [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/cmd_tools.py", line 72, in <module>: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/runner/item.py", line 15, in TestItem: Invalid type comment: (Callable[..., Any], List[Optional[Union[ModelProto, NodeProto]]]) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/report/coverage.py", line 19, in AttrCoverage: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/report/coverage.py", line 23, in AttrCoverage: Invalid type comment: (onnx.AttributeProto) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/report/coverage.py", line 36, in NodeCoverage: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/report/coverage.py", line 40, in NodeCoverage: Invalid type comment: (onnx.NodeProto) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/report/coverage.py", line 53, in Coverage: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/report/coverage.py", line 59, in Coverage: Invalid type comment: (onnx.NodeProto, Text) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/report/coverage.py", line 62, in Coverage: Invalid type comment: (onnx.GraphProto, Text) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/report/coverage.py", line 66, in Coverage: Invalid type comment: (onnx.ModelProto, Text) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/report/coverage.py", line 69, in Coverage: Invalid type comment: (onnx.ModelProto, Text) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/backend/test/report/coverage.py", line 73, in Coverage: Invalid type comment: (IO[Text]) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/tools/net_drawer.py", line 38, in <module>: Invalid type comment: (Text) -> Text [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/tools/net_drawer.py", line 43, in <module>: Invalid type comment: (Text) -> Text [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/tools/net_drawer.py", line 50, in <module>: Invalid type comment: (bool, **Any) -> _NodeProducer [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/tools/net_drawer.py", line 51, in GetOpNodeProducer: Invalid type comment: (NodeProto, int) -> pydot.Node [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/tools/net_drawer.py", line 111, in <module>: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/elu_test.py", line 8, in TestRelu: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/numpy_helper_test.py", line 15, in TestNumpyHelper: Invalid type comment: (np.number) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/numpy_helper_test.py", line 22, in TestNumpyHelper: Invalid type comment: (np.number) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/numpy_helper_test.py", line 33, in TestNumpyHelper: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/numpy_helper_test.py", line 36, in TestNumpyHelper: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/numpy_helper_test.py", line 39, in TestNumpyHelper: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/numpy_helper_test.py", line 42, in TestNumpyHelper: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/numpy_helper_test.py", line 45, in TestNumpyHelper: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/numpy_helper_test.py", line 48, in TestNumpyHelper: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/numpy_helper_test.py", line 51, in TestNumpyHelper: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/numpy_helper_test.py", line 54, in TestNumpyHelper: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/numpy_helper_test.py", line 57, in TestNumpyHelper: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/numpy_helper_test.py", line 64, in TestNumpyHelper: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/numpy_helper_test.py", line 67, in TestNumpyHelper: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/numpy_helper_test.py", line 70, in TestNumpyHelper: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/test_backend_test.py", line 83, in <module>: Invalid type comment: (ModelProto) -> bool [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/checker_test.py", line 24, in TestChecker: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/checker_test.py", line 30, in TestChecker: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/checker_test.py", line 45, in TestChecker: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/checker_test.py", line 63, in TestChecker: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/checker_test.py", line 73, in TestChecker: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/checker_test.py", line 92, in TestChecker: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/checker_test.py", line 110, in TestChecker: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/checker_test.py", line 122, in TestChecker: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/checker_test.py", line 135, in TestChecker: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/checker_test.py", line 142, in TestChecker: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/checker_test.py", line 154, in TestChecker: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/checker_test.py", line 159, in TestChecker: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/relu_test.py", line 8, in TestRelu: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 19, in TestHelperAttributeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 31, in TestHelperAttributeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 53, in TestHelperAttributeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 61, in TestHelperAttributeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 78, in TestHelperAttributeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 84, in TestHelperAttributeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 90, in TestHelperAttributeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 96, in TestHelperAttributeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 115, in TestHelperAttributeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 124, in TestHelperAttributeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 139, in TestHelperAttributeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 141, in test_is_attr_legal_verbose: Invalid type comment: (AttributeProto, AttributeProto.AttributeType, Text, Any) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 145, in test_is_attr_legal_verbose: Invalid type comment: (AttributeProto, AttributeProto.AttributeType, List[Any], Any) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 176, in TestHelperNodeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 185, in TestHelperNodeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 190, in TestHelperNodeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 205, in TestHelperNodeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 226, in TestHelperNodeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 231, in TestHelperNodeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 243, in TestHelperNodeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 251, in TestHelperNodeFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 267, in TestHelperTensorFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/helper_test.py", line 299, in TestHelperTensorFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/version_converter_test.py", line 32, in TestVersionConverter: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/version_converter_test.py", line 33, in test_backwards_incompatible: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/version_converter_test.py", line 45, in TestVersionConverter: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/version_converter_test.py", line 60, in TestVersionConverter: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/version_converter_test.py", line 61, in test_non_existent_op: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/schema_test.py", line 8, in TestSchema: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/schema_test.py", line 11, in TestSchema: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/schema_test.py", line 14, in TestSchema: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/basic_test.py", line 19, in TestBasicFunctions: Invalid type comment: () -> ModelProto [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/basic_test.py", line 25, in TestBasicFunctions: Invalid type comment: () -> TensorProto [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/basic_test.py", line 35, in TestBasicFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/basic_test.py", line 62, in TestBasicFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/basic_test.py", line 89, in TestBasicFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/onnx/test/basic_test.py", line 100, in TestBasicFunctions: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/tools/gen_coverage_report.py", line 13, in <module>: Invalid type comment: () -> argparse.Namespace [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/tools/gen_coverage_report.py", line 24, in <module>: Invalid type comment: (Text, Text) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/tools/gen_coverage_report.py", line 54, in <module>: Invalid type comment: (Text, Text, Text) -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/tools/gen_coverage_report.py", line 65, in <module>: Invalid type comment: () -> None [invalid-type-comment]
(mlperf)training_results_v0.6/Fujitsu/benchmarks/resnet/implementations/mxnet/3rdparty/onnx-tensorrt/third_party/onnx/tools/mypy-onnx.py", line 7, in <module>: Invalid type comment: () -> None [invalid-type-comment]
(DFO-Ocean-Navigator)Ocean-Data-Map-Project/utils/log.py", line 142, in <module>: Invalid type comment: datetime.datetime [invalid-type-comment]
(miyakogi)wdom/wdom/web_node.py", line 59, in WdomElement: Invalid type comment: WeakValueDictionary[_WdomIdType, WdomElement] [invalid-type-comment]
(miyakogi)wdom/wdom/event.py", line 52, in DataTransfer: Invalid type comment: Dict[str, DataTransfer] [invalid-type-comment]
(miyakogi)wdom/wdom/server/_tornado.py", line 23, in <module>: Invalid type comment: List[WSHandler] [invalid-type-comment]
(Ultimaker)Uranium/tests/Settings/ContainerTestPlugin/ContainerTestPlugin.py", line 104, in ContainerTestPlugin: Invalid type comment: Signal [invalid-type-comment]
(Ultimaker)Uranium/UM/Logger.py", line 14, in Logger: Invalid type comment: List[Logger] [invalid-type-comment]
(Ultimaker)Uranium/UM/JobQueue.py", line 94, in JobQueue: Invalid type comment: JobQueue [invalid-type-comment]
(Ultimaker)Uranium/UM/ConfigurationErrorMessage.py", line 56, in ConfigurationErrorMessage: Invalid type comment: ConfigurationErrorMessage [invalid-type-comment]
(Ultimaker)Uranium/UM/FileHandler/FileHandler.py", line 165, in FileHandler: Invalid type comment: FileHandler [invalid-type-comment]
(Ultimaker)Uranium/UM/Math/AxisAlignedBox.py", line 171, in AxisAlignedBox: Invalid type comment: AxisAlignedBox [invalid-type-comment]
(Ultimaker)Uranium/UM/Math/Vector.py", line 18, in Vector: Invalid type comment: Vector [invalid-type-comment]
(Ultimaker)Uranium/UM/Math/Vector.py", line 19, in Vector: Invalid type comment: Vector [invalid-type-comment]
(Ultimaker)Uranium/UM/Math/Vector.py", line 20, in Vector: Invalid type comment: Vector [invalid-type-comment]
(Ultimaker)Uranium/UM/Math/Vector.py", line 21, in Vector: Invalid type comment: Vector [invalid-type-comment]
(Ultimaker)Uranium/UM/View/View.py", line 23, in __init__: Invalid type comment: Controller [invalid-type-comment]
(Ultimaker)Uranium/UM/View/GL/OpenGLContext.py", line 143, in detectBestOpenGLVersion: Invalid type comment: Any [invalid-type-comment]
(Ultimaker)Uranium/UM/View/GL/OpenGL.py", line 292, in OpenGL: Invalid type comment: OpenGL [invalid-type-comment]
(Ultimaker)Uranium/UM/Qt/QtRenderer.py", line 46, in __init__: Invalid type comment: Controller [invalid-type-comment]
(Ultimaker)Uranium/UM/Qt/QtRenderer.py", line 47, in __init__: Invalid type comment: Scene [invalid-type-comment]
(Ultimaker)Uranium/UM/Qt/QtRenderer.py", line 62, in __init__: Invalid type comment: Optional[Camera] [invalid-type-comment]
(Ultimaker)Uranium/UM/Qt/QtRenderer.py", line 186, in _initialize: Invalid type comment: ShaderProgram [invalid-type-comment]
(dcos)dcos/packages/dcos-integration-test/extra/test_meta.py", line 85, in test_test_groups: Invalid type comment: Mapping[str, List] [invalid-type-comment]
(chovanecm)sacredboard/sacredboard/app/process/process.py", line 14, in Process: Invalid type comment: List[Process] [invalid-type-comment]
(home-assistant)home-assistant/homeassistant/util/yaml/loader.py", line 30, in <module>: Invalid type comment: Dict[str, JSON_TYPE] [invalid-type-comment]
(tkukushkin)asynqp-consumer/src/asynqp_consumer/consumer.py", line 73, in __init__: Invalid type comment: Iterator[ConnectionParams] [invalid-type-comment]
(lopter)lightsd/apps/monolight/monolight/grids.py", line 34, in <module>: Invalid type comment: Set[MonomeGrid] [invalid-type-comment]
(googlefonts)fontbakery/Lib/fontbakery/sphinx_extensions/linkcode.py", line 49, in doctree_read: Invalid type comment: Set[str] [invalid-type-comment]
(jacebrowning)doorstop/doorstop/server/main.py", line 24, in <module>: Invalid type comment: ignore, set in `run`, read in the route functions [invalid-type-comment]
