(micropython)micropython/tests/micropython/viper_addr.py:20: error: Argument 1 to "bytearray" has incompatible type "str"; expected "Iterable[int]"  [arg-type]
(ZingBallyhoo)OverwatchDataManager/pyow/version.py:61: error: Argument 1 to "OverwatchVersionComplex" has incompatible type "**Dict[str, str]"; expected "Dict[str, str]"  [arg-type]
(HurricaneLabs)machinae/src/machinae/outputs.py:70: error: Argument 1 to "join" of "str" has incompatible type "Iterator[Tuple[Any, Any]]"; expected "Iterable[str]"  [arg-type]
(suminb)transporter/transporter/utils.py:91: error: Argument 2 to "transform" of "DictMapper" has incompatible type "Tuple[Tuple[str, str, Callable[[str], Any]], Tuple[str, str, Type[float]], Tuple[str, str, Type[float]]]"; expected "Optional[List[Any]]"  [arg-type]
(suminb)transporter/transporter/utils.py:104: error: Argument 2 to "transform" of "DictMapper" has incompatible type "Tuple[Tuple[str, str, Type[int]], Tuple[str, str, Callable[[Any], Any]]]"; expected "Optional[List[Any]]"  [arg-type]
(Bertrand256)dash-masternode-tool/src/test/ledger_transaction_test.py:206: error: Argument 1 to "to_bytes" of "int" has incompatible type "object"; expected "int"  [arg-type]
(Bertrand256)dash-masternode-tool/src/encrypted_files.py:91: error: Argument 1 to "Fernet" has incompatible type "ByteString"; expected "bytes"  [arg-type]
(SunDwarf)asyncqlio/asyncqlio/backends/postgresql/asyncpg.py:135: error: Argument 2 to "get_param_query" has incompatible type "Optional[Mapping[str, Any]]"; expected "Dict[Any, Any]"  [arg-type]
(SunDwarf)asyncqlio/asyncqlio/backends/postgresql/asyncpg.py:155: error: Argument 2 to "get_param_query" has incompatible type "Optional[Mapping[str, Any]]"; expected "Dict[Any, Any]"  [arg-type]
(xpac1985)pyASA/pyASA/rulelogging.py:154: error: Argument 1 to "RuleLogging" has incompatible type "int"; expected "LogLevel"  [arg-type]
(xpac1985)pyASA/pyASA/rulelogging.py:154: error: Argument 2 to "RuleLogging" has incompatible type "LogLevel"; expected "int"  [arg-type]
(OpenBapul)hml-equation-parser/hml_equation_parser/hmlParser.py:118: error: Argument 1 to "extract2HtmlStr" has incompatible type "str"; expected "ElementTree"  [arg-type]
(pdjstone)cloudpets-web-bluetooth/cp_decode.py:36: error: Argument 1 to "memoryview" has incompatible type "array[int]"; expected "Union[bytes, bytearray, memoryview]"  [arg-type]
(pdjstone)cloudpets-web-bluetooth/cp_decode.py:38: error: Argument 1 to "memoryview" has incompatible type "array[int]"; expected "Union[bytes, bytearray, memoryview]"  [arg-type]
(pdjstone)cloudpets-web-bluetooth/cp_decode.py:52: error: Argument 1 to "writeframes" of "Wave_write" has incompatible type "array[int]"; expected "bytes"  [arg-type]
(pdjstone)cloudpets-web-bluetooth/cp_encode.py:77: error: Argument 1 to "hexlify" has incompatible type "Array[c_uint8]"; expected "bytes"  [arg-type]
(physera)onelogin-aws-cli/onelogin_aws_cli/configuration.py:129: error: Argument "fallback" to "getboolean" of "RawConfigParser" has incompatible type "int"; expected "bool"  [arg-type]
(paulcwatts)drf-json-schema/rest_framework_json_schema/schema.py:152: error: Argument 1 to "OrderedDict" has incompatible type "Tuple[Tuple[str, str], Tuple[str, str]]"; expected "Iterable[Tuple[str, Dict[Any, Any]]]"  [arg-type]
(Drowrin)Weeabot/cogs/anilist.py:38: error: Argument 1 to "parse" has incompatible type "datetime"; expected "Union[bytes, str, IO[str], IO[Any]]"  [arg-type]
(Andrew-Shay)Neuron/neuron/__init__.py:80: error: Argument "delay" to "RotatingFileHandler" has incompatible type "int"; expected "bool"  [arg-type]
(zdict)zdict/zdict/dictionaries/spanish.py:141: error: Argument 1 to "append" of "list" has incompatible type "Tuple[Any]"; expected "Tuple[Any, Any, Any]"  [arg-type]
(libnano)libnano/libnano/fileio/gb_writer_b.py:90: error: Argument 2 to "multiline_spaces" has incompatible type "bytes"; expected "str"  [arg-type]
(libnano)libnano/libnano/fileio/gb_writer_b.py:128: error: Argument 2 to "multiline_spaces" has incompatible type "bytes"; expected "str"  [arg-type]
(libnano)libnano/libnano/fileio/gb_writer_b.py:149: error: Argument 2 to "multiline_spaces" has incompatible type "bytes"; expected "str"  [arg-type]
(libnano)libnano/libnano/fileio/gb_writer_b.py:151: error: Argument 2 to "multiline_spaces" has incompatible type "bytes"; expected "str"  [arg-type]
(libnano)libnano/libnano/fileio/gb_writer_b.py:153: error: Argument 2 to "multiline_spaces" has incompatible type "bytes"; expected "str"  [arg-type]
(libnano)libnano/libnano/fileio/gb_writer_b.py:169: error: Argument 2 to "multiline_spaces" has incompatible type "bytes"; expected "str"  [arg-type]
(libnano)libnano/libnano/fileio/gb_writer_b.py:174: error: Argument 2 to "multiline_spaces" has incompatible type "bytes"; expected "str"  [arg-type]
(libnano)libnano/libnano/fileio/gb_writer_b.py:205: error: Argument 1 to "multiline" has incompatible type "bytes"; expected "str"  [arg-type]
(libnano)libnano/libnano/fileio/gb_writer_b.py:205: error: Argument 2 to "multiline" has incompatible type "bytes"; expected "str"  [arg-type]
(libnano)libnano/libnano/fileio/gb_writer_b.py:212: error: Argument 1 to "multiline_spaces" has incompatible type "bytes"; expected "str"  [arg-type]
(libnano)libnano/libnano/fileio/gb_writer_b.py:212: error: Argument 2 to "multiline_spaces" has incompatible type "bytes"; expected "str"  [arg-type]
(libnano)libnano/libnano/fileio/gb_writer_b.py:225: error: Argument 1 to "multiline" has incompatible type "bytes"; expected "str"  [arg-type]
(libnano)libnano/libnano/fileio/gb_writer_b.py:225: error: Argument 2 to "multiline" has incompatible type "bytes"; expected "str"  [arg-type]
(libnano)libnano/libnano/fileio/gb_writer_b.py:232: error: Argument 1 to "multiline_spaces" has incompatible type "bytes"; expected "str"  [arg-type]
(libnano)libnano/libnano/fileio/gb_writer_b.py:232: error: Argument 2 to "multiline_spaces" has incompatible type "bytes"; expected "str"  [arg-type]
(libnano)libnano/libnano/helpers/jsonbytes.py:23: error: Argument 1 to "base_decode_list" has incompatible type "Union[Tuple[Any, ...], List[Any]]"; expected "List[Any]"  [arg-type]
(xlevus)python-diana/diana/injector.py:189: error: Argument 1 to "update_wrapper" has incompatible type "Dependencies"; expected "Callable[..., Any]"  [arg-type]
(e-gun)HipparchiaServer/server/searching/searchdispatching.py:170: error: Argument 1 to "list" has incompatible type "Tuple[List[Any], List[Any], Any]"; expected "Iterable[int]"  [arg-type]
(e-gun)HipparchiaServer/server/textsandindices/textandindiceshelperfunctions.py:217: error: Argument 1 to "list" of "SyncManager" has incompatible type "Set[Any]"; expected "Sequence[<nothing>]"  [arg-type]
(e-gun)HipparchiaServer/server/hipparchiaobjects/searchfunctionobjects.py:128: error: Argument 1 to "loads" has incompatible type "Tuple[Any, ...]"; expected "bytes"  [arg-type]
(TeamSpen210)srctools/srctools/logger.py:93: error: Argument 2 to "LogMessage" has incompatible type "Tuple[object, ...]"; expected "Tuple[object]"  [arg-type]
(flyinactor91)AVWX-Engine/avwx/service.py:63: error: Argument "data" to "urlopen" has incompatible type "Dict[Any, Any]"; expected "Optional[bytes]"  [arg-type]
(flyinactor91)AVWX-Engine/avwx/__init__.py:118: error: Argument 1 to "metar" has incompatible type "ReportTrans"; expected "MetarTrans"  [arg-type]
(flyinactor91)AVWX-Engine/avwx/__init__.py:127: error: Argument 1 to "metar" has incompatible type "ReportData"; expected "MetarData"  [arg-type]
(flyinactor91)AVWX-Engine/avwx/__init__.py:156: error: Argument 1 to "taf" has incompatible type "ReportData"; expected "TafData"  [arg-type]
(flyinactor91)AVWX-Engine/avwx/pirep.py:64: error: Argument 3 to "Location" has incompatible type "str"; expected "Number"  [arg-type]
(flyinactor91)AVWX-Engine/avwx/pirep.py:64: error: Argument 4 to "Location" has incompatible type "str"; expected "Number"  [arg-type]
(flyinactor91)AVWX-Engine/avwx/pirep.py:111: error: Argument 1 to "Turbulance" has incompatible type "**Dict[str, str]"; expected "Number"  [arg-type]
(flyinactor91)AVWX-Engine/avwx/pirep.py:126: error: Argument 1 to "Icing" has incompatible type "**Dict[str, str]"; expected "Number"  [arg-type]
(flyinactor91)AVWX-Engine/avwx/pirep.py:192: error: Argument 1 to "PirepData" has incompatible type "**Dict[str, str]"; expected "Timestamp"  [arg-type]
(flyinactor91)AVWX-Engine/avwx/pirep.py:192: error: Argument 1 to "PirepData" has incompatible type "**Dict[str, str]"; expected "Number"  [arg-type]
(flyinactor91)AVWX-Engine/avwx/pirep.py:192: error: Argument 1 to "PirepData" has incompatible type "**Dict[str, str]"; expected "Icing"  [arg-type]
(flyinactor91)AVWX-Engine/avwx/pirep.py:192: error: Argument 1 to "PirepData" has incompatible type "**Dict[str, str]"; expected "Location"  [arg-type]
(flyinactor91)AVWX-Engine/avwx/pirep.py:192: error: Argument 1 to "PirepData" has incompatible type "**Dict[str, str]"; expected "Turbulance"  [arg-type]
(flyinactor91)AVWX-Engine/avwx/translate.py:98: error: Argument 1 to "get_cardinal_direction" has incompatible type "float"; expected "int"  [arg-type]
(flyinactor91)AVWX-Engine/avwx/translate.py:354: error: Argument 1 to "min_max_temp" has incompatible type "float"; expected "str"  [arg-type]
(flyinactor91)AVWX-Engine/avwx/translate.py:355: error: Argument 1 to "min_max_temp" has incompatible type "float"; expected "str"  [arg-type]
(flyinactor91)AVWX-Engine/avwx/translate.py:357: error: Argument 1 to "TafTrans" has incompatible type "**Dict[str, List[Any]]"; expected "str"  [arg-type]
(flyinactor91)AVWX-Engine/avwx/translate.py:357: error: Argument 1 to "TafTrans" has incompatible type "**Dict[str, List[Any]]"; expected "Dict[Any, Any]"  [arg-type]
(myd7349)Ongoing-Study/python/btdload.py:107: error: Argument 1 to "urlparse" has incompatible type "AnyStr"; expected "str"  [arg-type]
(alberthdev)spasm-ng/tests/test-runner.py:220: error: Argument 1 to "len" has incompatible type "Iterable[str]"; expected "Sized"  [arg-type]
(tkajder)elian-translator/elian.py:177: error: Argument 1 to "_word_to_upper_middle_lower" of "ElianScript" has incompatible type "List[ElianCharacter]"; expected "str"  [arg-type]
(ggravlingen)pytradfri/tests/test_device.py:293: error: Argument 1 to "len" has incompatible type "int"; expected "Sized"  [arg-type]
(ggravlingen)pytradfri/tests/test_device.py:294: error: Argument 1 to "len" has incompatible type "int"; expected "Sized"  [arg-type]
(neitsa)PrepareLanding/tools/appveyor/download_dependencies.py:303: error: Argument 1 to "setpassword" of "ZipFile" has incompatible type "str"; expected "bytes"  [arg-type]
(neitsa)PrepareLanding/tools/appveyor/download_dependencies.py:318: error: Argument 1 to "setpassword" of "ZipFile" has incompatible type "str"; expected "bytes"  [arg-type]
(wtsi-hgi)hgi-systems/scripts/used-images/investigator/investigator.py:203: error: Argument 2 to "_find_references" has incompatible type "Dict[str, List[str]]"; expected "Dict[str, Iterable[str]]"  [arg-type]
(wtsi-hgi)hgi-systems/scripts/used-images/investigator/investigator.py:204: error: Argument 2 to "_find_references" has incompatible type "Dict[str, List[str]]"; expected "Dict[str, Iterable[str]]"  [arg-type]
(mara)mara-db/mara_db/auto_migration.py:119: error: Argument 2 to "isinstance" has incompatible type "_SpecialForm"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"  [arg-type]
(OFAI)hub-toolbox-python3/hub_toolbox/goodman_kruskal.py:314: error: Argument 1 to "len" has incompatible type "int"; expected "Sized"  [arg-type]
(BSI-CERT-Bund)cortex-analyzers/analyzers/MISP/mispclient.py:35: error: Argument 1 to "isfile" has incompatible type "Union[List[Any], bool]"; expected "Union[bytes, str, _PathLike[Any]]"  [arg-type]
(BSI-CERT-Bund)cortex-analyzers/analyzers/VMRay/vmrayclient.py:43: error: Argument 1 to "isfile" has incompatible type "Union[str, bool]"; expected "Union[bytes, str, _PathLike[Any]]"  [arg-type]
(pipermerriam)ethereum-abi-utils/tests/common/unit.py:47: error: Argument 1 to "rjust" of "str" has incompatible type "str"; expected "int"  [arg-type]
(pipermerriam)ethereum-abi-utils/tests/common/unit.py:50: error: Argument 1 to "ljust" of "str" has incompatible type "str"; expected "int"  [arg-type]
(pipermerriam)ethereum-abi-utils/tests/common/unit.py:52: error: Argument 1 to "rjust" of "str" has incompatible type "str"; expected "int"  [arg-type]
(linusg)rpi-backlight/rpi_backlight/__init__.py:38: error: Argument 1 to "Path" has incompatible type "Union[str, bytes, Path]"; expected "Union[str, _PathLike[str]]"  [arg-type]
(linusg)rpi-backlight/rpi_backlight/__init__.py:141: error: Argument 1 to "_denormalize_brightness" of "Backlight" has incompatible type "float"; expected "int"  [arg-type]
(linusg)rpi-backlight/rpi_backlight/__init__.py:145: error: Argument 1 to "_denormalize_brightness" of "Backlight" has incompatible type "float"; expected "int"  [arg-type]
(sdementen)gnucash-utilities/tests/test_basic.py:8: error: Argument 1 to "__call__" of "_StreamWriter" has incompatible type "TextIO"; expected "IO[bytes]"  [arg-type]
(OpenMineMods)OpenMineMods/API/MultiMC.py:117: error: Argument 1 to "groups" of "Match" has incompatible type "int"; expected "str"  [arg-type]
(pauloalves86)go_dino/dino_api.py:44: error: Argument 4 to "compute_speed" of "Board" has incompatible type "List[int]"; expected "List[float]"  [arg-type]
(olivierfriard)BORIS/src/boris_cli.py:246: error: Argument 3 to "load_aggregated_events_in_db" has incompatible type "Dict[Any, Any]"; expected "List[Any]"  [arg-type]
(tmerr)bank_wrangler/bank_wrangler/report/__init__.py:81: error: Argument 1 to "map" has incompatible type overloaded function; expected "Callable[[str], AnyStr]"  [arg-type]
(tmerr)bank_wrangler/bank_wrangler/report/__init__.py:82: error: Argument 1 to "map" has incompatible type overloaded function; expected "Callable[[str], AnyStr]"  [arg-type]
(sloria)aiohttp_utils/aiohttp_utils/routing.py:131: error: Argument 1 to "import_module" has incompatible type "Union[str, bytes]"; expected "str"  [arg-type]
(sloria)aiohttp_utils/aiohttp_utils/routing.py:239: error: Argument 1 to "import_module" has incompatible type "Union[str, bytes]"; expected "str"  [arg-type]
(sloria)aiohttp_utils/aiohttp_utils/routing.py:256: error: Argument 2 to "getattr" has incompatible type "Union[str, bytes]"; expected "str"  [arg-type]
(Pitt-CSC)PittAPI/tests/people_test.py:24: error: Argument 1 to "skip" has incompatible type "Type[PeopleTest]"; expected "str"  [arg-type]
(Pitt-CSC)PittAPI/tests/library_test.py:24: error: Argument 1 to "skip" has incompatible type "Type[LibraryTest]"; expected "str"  [arg-type]
(Pitt-CSC)PittAPI/tests/news_test.py:24: error: Argument 1 to "skip" has incompatible type "Type[NewsTest]"; expected "str"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:26: error: Argument 1 to "int" has incompatible type "Union[str, int, bytes]"; expected "Union[str, bytes, bytearray]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:28: error: Argument 1 to "len" has incompatible type "Union[str, int, bytes]"; expected "Sized"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:29: error: Argument 1 to "len" has incompatible type "Union[str, int, bytes]"; expected "Sized"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:33: error: Argument 1 to "len" has incompatible type "Union[str, int, bytes]"; expected "Sized"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:38: error: Argument 1 to "from_bytes" of "int" has incompatible type "Union[str, int, bytes]"; expected "Sequence[int]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:44: error: Argument 1 to "bin" has incompatible type "Union[str, int, bytes]"; expected "Union[int, _SupportsIndex]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:58: error: Argument 1 to "int" has incompatible type "Union[str, int, bytes]"; expected "Union[str, bytes, bytearray]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:64: error: Argument 1 to "from_bytes" of "int" has incompatible type "Union[str, int, bytes]"; expected "Sequence[int]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:77: error: Argument 1 to "len" has incompatible type "Union[str, int, bytes]"; expected "Sized"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:78: error: Argument 1 to "len" has incompatible type "Union[str, int, bytes]"; expected "Sized"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:82: error: Argument 1 to "len" has incompatible type "Union[str, int, bytes]"; expected "Sized"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/entropy.py:87: error: Argument 1 to "int" has incompatible type "Union[str, int, bytes]"; expected "Union[str, bytes, bytearray]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:74: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:75: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:76: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:77: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:82: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:87: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(fametrano)BitcoinBlockchainTechnology/btclib/rfc6979.py:88: error: Argument 3 to "new" has incompatible type "Callable[[Any], Any]"; expected "Union[str, Callable[[], Any], Module, None]"  [arg-type]
(CoolProp)CoolProp/wrappers/Python/CoolProp/Plots/PsychChart.py:185: error: Argument 1 to "write" of "IO" has incompatible type "bytes"; expected "str"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:219: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "bool"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:219: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "Optional[Type[JSONEncoder]]"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:219: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "Optional[Tuple[str, str]]"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:219: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "Optional[Callable[[Any], Any]]"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:244: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "bool"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:244: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "Optional[Type[JSONEncoder]]"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:244: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "Optional[Tuple[str, str]]"  [arg-type]
(CoolProp)CoolProp/dev/scripts/fit_rational_functions.py:244: error: Argument 2 to "dumps" has incompatible type "**Dict[str, int]"; expected "Optional[Callable[[Any], Any]]"  [arg-type]
(Leixb)jutge_cli/jutge_cli/commands/import_zip.py:105: error: Argument 1 to "symlink" has incompatible type "List[str]"; expected "Union[bytes, str, _PathLike[Any]]"  [arg-type]
(Leixb)jutge_cli/jutge_cli/commands/test.py:182: error: Argument 2 to "print_color" has incompatible type "str"; expected "Optional[List[Any]]"  [arg-type]
(gomjellie)SoongSiri/app/managers.py:197: error: Argument 1 to "verify_session" has incompatible type "Callable[[SessionManager, Any], Any]"; expected "SessionManager"  [arg-type]
(gomjellie)SoongSiri/app/managers.py:201: error: Argument 1 to "verify_session" has incompatible type "Callable[[SessionManager, Any, Any], Any]"; expected "SessionManager"  [arg-type]
(gomjellie)SoongSiri/app/managers.py:209: error: Argument 1 to "verify_session" has incompatible type "Callable[[SessionManager, Any], Any]"; expected "SessionManager"  [arg-type]
(gomjellie)SoongSiri/app/managers.py:215: error: Argument 1 to "verify_session" has incompatible type "Callable[[SessionManager, Any, Any], Any]"; expected "SessionManager"  [arg-type]
(gomjellie)SoongSiri/app/managers.py:221: error: Argument 1 to "verify_session" has incompatible type "Callable[[SessionManager, Any], Any]"; expected "SessionManager"  [arg-type]
(gomjellie)SoongSiri/app/managers.py:227: error: Argument 1 to "verify_session" has incompatible type "Callable[[SessionManager, Any], Any]"; expected "SessionManager"  [arg-type]
(puhitaku)typedmarshal/typedmarshal/model.py:190: error: Argument 2 to "_unmarshal_with_type_check" of "MarshalModel" has incompatible type "TypeLike"; expected "Tuple[<nothing>]"  [arg-type]
(puhitaku)typedmarshal/typedmarshal/model.py:200: error: Argument 2 to "isinstance" has incompatible type "TypeLike"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"  [arg-type]
(puhitaku)typedmarshal/typedmarshal/model.py:215: error: Argument 1 to "load" has incompatible type "IOBase"; expected "_Reader"  [arg-type]
(drewm1980)multi_view_stereo_benchmark/reconstruct.py:12: error: Argument 1 to "append" of "list" has incompatible type "Path"; expected "str"  [arg-type]
(pvizeli)ha-ffmpeg/haffmpeg/core.py:136: error: Argument 2 to "run_in_executor" of "BaseEventLoop" has incompatible type "partial[Popen[str]]"; expected "Callable[..., None]"  [arg-type]
(Kane610)axis/axis/param_cgi.py:154: error: Argument 1 to "dict" has incompatible type "Generator[List[str], None, None]"; expected "Iterable[Tuple[<nothing>, <nothing>]]"  [arg-type]
(Kane610)axis/axis/pwdgrp_cgi.py:94: error: Argument 1 to "dict" has incompatible type "Generator[List[str], None, None]"; expected "Iterable[Tuple[<nothing>, <nothing>]]"  [arg-type]
(jhartz)gradefast/gradefast/events.py:139: error: Argument 1 has incompatible type "Event"; expected "T"  [arg-type]
(google)graphicsfuzz/third_party/thrift-py/src/main/scripts/transport/THttpClient.py:155: error: Argument 1 to "__withTimeout" has incompatible type "Callable[[THttpClient], Any]"; expected "THttpClient"  [arg-type]
(ros2)rclpy/rclpy/rclpy/publisher.py:67: error: Argument 2 to "isinstance" has incompatible type "MsgType"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"  [arg-type]
(JetBrains)kotlin-web-site/kotlin-website.py:468: error: Argument 4 to "run" of "Flask" has incompatible type "**Dict[str, Set[str]]"; expected "Union[int, str, None]"  [arg-type]
(JetBrains)kotlin-web-site/kotlin-website.py:468: error: Argument 4 to "run" of "Flask" has incompatible type "**Dict[str, Set[str]]"; expected "bool"  [arg-type]
(eecs280staff)autograder-sandbox/autograder_sandbox/autograder_sandbox.py:294: error: Argument "stdout" to "CompletedCommand" has incompatible type "IO[bytes]"; expected "FileIO"  [arg-type]
(eecs280staff)autograder-sandbox/autograder_sandbox/autograder_sandbox.py:295: error: Argument "stderr" to "CompletedCommand" has incompatible type "IO[bytes]"; expected "FileIO"  [arg-type]
(eecs280staff)autograder-sandbox/autograder_sandbox/autograder_sandbox.py:302: error: Argument "output" to "CalledProcessError" has incompatible type "FileIO"; expected "Union[bytes, str, None]"  [arg-type]
(eecs280staff)autograder-sandbox/autograder_sandbox/autograder_sandbox.py:302: error: Argument "stderr" to "CalledProcessError" has incompatible type "FileIO"; expected "Union[bytes, str, None]"  [arg-type]
(Josca)im/im/display.py:11: error: Argument 1 to "keypad" of "_CursesWindow" has incompatible type "int"; expected "bool"  [arg-type]
(Josca)im/im/display.py:12: error: Argument 1 to "nodelay" of "_CursesWindow" has incompatible type "int"; expected "bool"  [arg-type]
(rocky)python-xdis/xdis/util.py:63: error: Argument 1 to "dict" has incompatible type "Generator[List[object], None, None]"; expected "Iterable[Tuple[<nothing>, <nothing>]]"  [arg-type]
(rocky)python-xdis/xdis/util.py:67: error: Argument 1 to "dict" has incompatible type "Generator[List[Any], None, None]"; expected "Iterable[Tuple[<nothing>, <nothing>]]"  [arg-type]
(DiscordMusicBot)MusicBot/musicbot/__init__.py:83: error: Argument 2 to "insert" of "list" has incompatible type "Yikes"; expected "MetaPathFinder"  [arg-type]
(sassoftware)saspy/saspy/sasutil.py:92: error: Argument 1 to "proc_decorator" has incompatible type "Dict[<nothing>, <nothing>]"; expected "procDecorator"  [arg-type]
(sassoftware)saspy/saspy/sasutil.py:121: error: Argument 1 to "proc_decorator" has incompatible type "Dict[<nothing>, <nothing>]"; expected "procDecorator"  [arg-type]
(sassoftware)saspy/saspy/sasutil.py:150: error: Argument 1 to "proc_decorator" has incompatible type "Dict[<nothing>, <nothing>]"; expected "procDecorator"  [arg-type]
(sassoftware)saspy/saspy/sasutil.py:175: error: Argument 1 to "proc_decorator" has incompatible type "Dict[<nothing>, <nothing>]"; expected "procDecorator"  [arg-type]
(sassoftware)saspy/saspy/sasml.py:88: error: Argument 1 to "proc_decorator" has incompatible type "Set[str]"; expected "procDecorator"  [arg-type]
(sassoftware)saspy/saspy/sasml.py:117: error: Argument 1 to "proc_decorator" has incompatible type "Dict[<nothing>, <nothing>]"; expected "procDecorator"  [arg-type]
(sassoftware)saspy/saspy/sasml.py:142: error: Argument 1 to "proc_decorator" has incompatible type "Set[str]"; expected "procDecorator"  [arg-type]
(sassoftware)saspy/saspy/sasml.py:167: error: Argument 1 to "proc_decorator" has incompatible type "Set[str]"; expected "procDecorator"  [arg-type]
(sassoftware)saspy/saspy/sasml.py:202: error: Argument 1 to "proc_decorator" has incompatible type "Set[str]"; expected "procDecorator"  [arg-type]
(sassoftware)saspy/saspy/sasml.py:239: error: Argument 1 to "proc_decorator" has incompatible type "Set[str]"; expected "procDecorator"  [arg-type]
(sassoftware)saspy/saspy/sastabulate.py:276: error: Argument 1 to "update" of "dict" has incompatible type "Dict[str, Dict[Any, Any]]"; expected "Mapping[str, str]"  [arg-type]
(sassoftware)saspy/saspy/sasqc.py:86: error: Argument 1 to "proc_decorator" has incompatible type "Dict[<nothing>, <nothing>]"; expected "procDecorator"  [arg-type]
(sassoftware)saspy/saspy/sasqc.py:108: error: Argument 1 to "proc_decorator" has incompatible type "Dict[<nothing>, <nothing>]"; expected "procDecorator"  [arg-type]
(sassoftware)saspy/saspy/sasqc.py:129: error: Argument 1 to "proc_decorator" has incompatible type "Dict[<nothing>, <nothing>]"; expected "procDecorator"  [arg-type]
(sassoftware)saspy/saspy/sasqc.py:174: error: Argument 1 to "proc_decorator" has incompatible type "Dict[<nothing>, <nothing>]"; expected "procDecorator"  [arg-type]
(webpwnized)cryptography/hill-involutary-keys.py:104: error: Argument 2 to "get_adjunct" has incompatible type "int"; expected "List[Any]"  [arg-type]
(eseifert)madam/madam/vector.py:145: error: Argument 3 to "__remove_elements" of "SVGProcessor" has incompatible type "Callable[[Element], Union[str, List[Element]]]"; expected "Callable[[Element], bool]"  [arg-type]
(eseifert)madam/madam/vector.py:150: error: Argument 3 to "__remove_elements" of "SVGProcessor" has incompatible type "Callable[[Element], Union[List[Element], bool]]"; expected "Callable[[Element], bool]"  [arg-type]
(eseifert)madam/madam/vector.py:154: error: Argument 3 to "__remove_elements" of "SVGProcessor" has incompatible type "Callable[[Element], Union[List[Element], bool]]"; expected "Callable[[Element], bool]"  [arg-type]
(eseifert)madam/madam/vector.py:159: error: Argument 3 to "__remove_elements" of "SVGProcessor" has incompatible type "Callable[[Element], Union[List[Element], bool]]"; expected "Callable[[Element], bool]"  [arg-type]
(eseifert)madam/madam/vector.py:172: error: Argument 3 to "__remove_elements" of "SVGProcessor" has incompatible type "Callable[[Element], str]"; expected "Callable[[Element], bool]"  [arg-type]
(eseifert)madam/madam/vector.py:175: error: Argument 3 to "__remove_elements" of "SVGProcessor" has incompatible type "Callable[[Element], str]"; expected "Callable[[Element], bool]"  [arg-type]
(eseifert)madam/madam/vector.py:178: error: Argument 3 to "__remove_elements" of "SVGProcessor" has incompatible type "Callable[[Element], str]"; expected "Callable[[Element], bool]"  [arg-type]
(eseifert)madam/madam/exif.py:77: error: Argument 1 to "time" has incompatible type "*Iterator[int]"; expected "Optional[tzinfo]"  [arg-type]
(sipb)homeworld/platform/spire/src/access.py:202: error: Argument 1 to "call_etcdctl" has incompatible type "Tuple[str, ...]"; expected "List[Any]"  [arg-type]
(corpnewt)CorpBot.py/Cogs/Actions.py:223: error: Argument 1 to "computeAction" has incompatible type "Type[eating]"; expected "actionable"  [arg-type]
(corpnewt)CorpBot.py/Cogs/Actions.py:231: error: Argument 1 to "computeAction" has incompatible type "Type[drinking]"; expected "actionable"  [arg-type]
(corpnewt)CorpBot.py/Cogs/Actions.py:239: error: Argument 1 to "computeAction" has incompatible type "Type[booping]"; expected "actionable"  [arg-type]
(corpnewt)CorpBot.py/Cogs/Actions.py:250: error: Argument 1 to "computeAction" has incompatible type "Type[spooky]"; expected "actionable"  [arg-type]
(corpnewt)CorpBot.py/Cogs/Actions.py:258: error: Argument 1 to "computeAction" has incompatible type "Type[highfives]"; expected "actionable"  [arg-type]
(corpnewt)CorpBot.py/Cogs/Actions.py:266: error: Argument 1 to "computeAction" has incompatible type "Type[petting]"; expected "actionable"  [arg-type]
(mancellin)capytaine/capytaine/meshes/symmetric.py:283: error: Argument 1 to "len" has incompatible type "Iterable[float]"; expected "Sized"  [arg-type]
(wongcyrus)ExcelLexBot/builder/converter/ExcelConverterBase.py:36: error: Argument 1 to "decode" has incompatible type "str"; expected "bytes"  [arg-type]
(eliostvs)tomate/tests/test_config.py:22: error: Argument 3 to "__call__" of "_patcher" has incompatible type "**Dict[str, object]"; expected "bool"  [arg-type]
(eliostvs)tomate/tests/test_config.py:116: error: Argument 3 to "__call__" of "_patcher" has incompatible type "**Dict[str, object]"; expected "bool"  [arg-type]
(AJudge-team)AJudge/validator/string_validator.py:10: error: Argument 1 to "validate" of "StringValidator" has incompatible type "List[str]"; expected "str"  [arg-type]
(AJudge-team)AJudge/validator/string_validator.py:10: error: Argument 2 to "validate" of "StringValidator" has incompatible type "List[str]"; expected "str"  [arg-type]
(bosondata)chrome-prerender/prerender/mhtml.py:23: error: Argument 1 to "b64encode" has incompatible type "str"; expected "bytes"  [arg-type]
(jjkester)moneybird-python/moneybird/authentication.py:131: error: Argument 1 to "OAuthError" has incompatible type "List[str]"; expected "str"  [arg-type]
(jjkester)moneybird-python/moneybird/authentication.py:131: error: Argument 2 to "OAuthError" has incompatible type "Union[List[str], str]"; expected "Optional[str]"  [arg-type]
(PetterKraabol)Twitch-Chat-Downloader/tcd/settings.py:53: error: Argument 1 to "write" of "Settings" has incompatible type "Path"; expected "str"  [arg-type]
(PetterKraabol)Twitch-Chat-Downloader/tcd/settings.py:81: error: Argument 1 to "write" of "Settings" has incompatible type "Path"; expected "str"  [arg-type]
(PetterKraabol)Twitch-Chat-Downloader/tcd/settings.py:84: error: Argument 1 to "load" of "Settings" has incompatible type "Path"; expected "str"  [arg-type]
(PetterKraabol)Twitch-Chat-Downloader/tcd/settings.py:95: error: Argument 1 to "write" of "Settings" has incompatible type "Path"; expected "str"  [arg-type]
(PetterKraabol)Twitch-Chat-Downloader/tcd/settings.py:97: error: Argument 1 to "load" of "Settings" has incompatible type "Path"; expected "str"  [arg-type]
(PetterKraabol)Twitch-Chat-Downloader/tcd/settings.py:114: error: Argument 1 to "write" of "Settings" has incompatible type "Path"; expected "str"  [arg-type]
(miracle2k)k8s-snapshots/k8s_snapshots/snapshot.py:36: error: Argument 2 to "load_snapshots" has incompatible type "List[Any]"; expected "Set[Any]"  [arg-type]
(cbozi)edge-server-placement/src/run_and_print.py:61: error: Argument 1 to "run_with_parameters" has incompatible type "Dict[str, MIPServerPlacer]"; expected "Dict[str, ServerPlacer]"  [arg-type]
(ESultanik)lenticrypt/tests/test_main.py:40: error: Argument 1 to "make_plaintexts" has incompatible type "Tuple[IO[bytes], ...]"; expected "Sequence[BinaryIO]"  [arg-type]
(ESultanik)lenticrypt/tests/test_main.py:44: error: Argument 1 to "make_keys" has incompatible type "Tuple[IO[bytes], ...]"; expected "Sequence[BinaryIO]"  [arg-type]
(fasiha)ebisu/ebisu/tests/test_ebisu.py:149: error: Argument 1 to "loadTestsFromModule" of "TestLoader" has incompatible type "TestEbisu"; expected Module  [arg-type]
(tonnie17)flowlight/flowlight/core/connection.py:106: error: Argument 1 to "ensure_connect" has incompatible type "Callable[[Connection, Command], Any]"; expected "Connection"  [arg-type]
(tonnie17)flowlight/flowlight/core/connection.py:110: error: Argument 1 to "ensure_connect" has incompatible type "Callable[[Connection, Command], Coroutine[Any, Any, Any]]"; expected "Connection"  [arg-type]
(tonnie17)flowlight/flowlight/core/connection.py:176: error: Argument 1 to "ensure_connect" has incompatible type "Callable[[Connection], Any]"; expected "Connection"  [arg-type]
(jesopo)bitbot/src/EventManager.py:97: error: Argument 5 to "_hook" of "EventRoot" has incompatible type "List[Tuple[str, Any]]"; expected "Dict[Any, Any]"  [arg-type]
(jesopo)bitbot/src/EventManager.py:149: error: Argument 5 to "EventHook" has incompatible type "Dict[Any, Any]"; expected "List[Tuple[str, Any]]"  [arg-type]
(OddBloke)jenkins-job-linter/tests/test_linters.py:35: error: Argument 1 to "list" has incompatible type "Iterator[Tuple[str, ...]]"; expected "Iterable[str]"  [arg-type]
(mesgarpour)T-CARER/ReadersWriters/_TextFile.py:193: error: Argument 1 to "__append_pretty_dict" of "TextFile" has incompatible type "Dict[Any, Any]"; expected "Callable[[Dict[Any, Any], CollectionsOrderedDict?], None]"  [arg-type]
(mesgarpour)T-CARER/Stats/YeoJohnson.py:100: error: Argument "derivative" to "fit" of "YeoJohnson" has incompatible type "int"; expected "Callable[[int, float], None]"  [arg-type]
(mesgarpour)T-CARER/Features/FeatureParserThread.py:65: error: Argument 1 to "map" has incompatible type "Type[int]"; expected "Callable[[object], int]"  [arg-type]
(mesgarpour)T-CARER/Features/FeatureParserThread.py:65: error: Argument 1 to "map" has incompatible type "Type[int]"; expected "Callable[[object], object]"  [arg-type]
(sheriferson)simplestatistics/simplestatistics/statistics/mode.py:45: error: Argument 1 to "len" has incompatible type "Union[int, List[Any]]"; expected "Sized"  [arg-type]
(sheriferson)simplestatistics/simplestatistics/statistics/median.py:42: error: Argument 1 to "float" has incompatible type "Union[int, float, List[Any]]"; expected "Union[SupportsFloat, _SupportsIndex, str, bytes, bytearray]"  [arg-type]
(sheriferson)simplestatistics/simplestatistics/statistics/median.py:46: error: Argument 1 to "len" has incompatible type "Union[int, float, List[Any]]"; expected "Sized"  [arg-type]
(sheriferson)simplestatistics/simplestatistics/statistics/median.py:48: error: Argument 1 to "len" has incompatible type "Union[int, float, List[Any]]"; expected "Sized"  [arg-type]
(sheriferson)simplestatistics/simplestatistics/statistics/median.py:49: error: Argument 1 to "len" has incompatible type "Union[int, float, List[Any]]"; expected "Sized"  [arg-type]
(sheriferson)simplestatistics/simplestatistics/statistics/median.py:52: error: Argument 1 to "len" has incompatible type "Union[int, float, List[Any]]"; expected "Sized"  [arg-type]
(SunDwarf)Kyoukai/kyoukai/util.py:69: error: Argument "cls" to "dumps" has incompatible type "Optional[JSONEncoder]"; expected "Optional[Type[JSONEncoder]]"  [arg-type]
(SunDwarf)Kyoukai/kyoukai/util.py:102: error: Argument 2 to "isinstance" has incompatible type "Response"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"  [arg-type]
(SunDwarf)Kyoukai/kyoukai/testing.py:119: error: Argument 1 to "to_wsgi_environment" has incompatible type "Dict[Any, Any]"; expected "List[Any]"  [arg-type]
(SunDwarf)Kyoukai/kyoukai/testing.py:119: error: Argument "body" to "to_wsgi_environment" has incompatible type "str"; expected "Optional[BytesIO]"  [arg-type]
(SunDwarf)Kyoukai/kyoukai/route.py:273: error: Argument 1 to "check_route_args" of "Route" has incompatible type "Container[Any]"; expected "Optional[Dict[Any, Any]]"  [arg-type]
(Cmoen11)BuffBot/BuffBot/playlist.py:70: error: Argument 1 to "make_playlist" of "Queue" has incompatible type "object"; expected "Node"  [arg-type]
(GoVanguard)check-user-pwned-dradis/haveIBeenPwndDradis.py:61: error: Argument 2 to "createNode" of "HaveIBeenPwndDradis" has incompatible type "str"; expected "int"  [arg-type]
(CZ-NIC)knot-resolver/tests/pytests/proxy.py:123: error: Argument 1 to "contextmanager" has incompatible type "Callable[[str, TLSProxy, Optional[Dict[Any, Any]], Optional[Dict[Any, Any]]], Kresd]"; expected "Callable[..., Iterator[<nothing>]]"  [arg-type]
(arnomoonens)DeepRL/yarll/agents/actorcritic/actor_critic.py:26: error: Argument 1 to "list" has incompatible type "Sequence[int]"; expected "Iterable[None]"  [arg-type]
(arnomoonens)DeepRL/yarll/agents/actorcritic/actor_critic.py:182: error: Argument 1 to "list" has incompatible type "Sequence[int]"; expected "Iterable[None]"  [arg-type]
(erp12)pyshgp/pyshgp/push/types.py:111: error: Argument 2 to "PushType" has incompatible type "Tuple[Type[int], Any, Any, Any, Any]"; expected "Tuple[type]"  [arg-type]
(erp12)pyshgp/pyshgp/push/types.py:112: error: Argument 2 to "PushType" has incompatible type "Tuple[Type[float], Any, Any, Any]"; expected "Tuple[type]"  [arg-type]
(erp12)pyshgp/pyshgp/push/types.py:113: error: Argument 2 to "PushType" has incompatible type "Tuple[Type[str], Any]"; expected "Tuple[type]"  [arg-type]
(erp12)pyshgp/pyshgp/push/types.py:114: error: Argument 2 to "PushType" has incompatible type "Tuple[Type[bool], Any]"; expected "Tuple[type]"  [arg-type]
(aio-libs)multidict/benchmarks/becnhmark.py:119: error: Argument 1 to "len" has incompatible type "object"; expected "Sized"  [arg-type]
(aio-libs)multidict/benchmarks/istr.py:63: error: Argument 1 to "len" has incompatible type "object"; expected "Sized"  [arg-type]
(PaulSonOfLars)tgbot/tg_bot/modules/helper_funcs/misc.py:57: error: Argument 1 to "append" of "list" has incompatible type "Tuple[EqInlineKeyboardButton]"; expected "Tuple[EqInlineKeyboardButton, EqInlineKeyboardButton]"  [arg-type]
(anthok)overwatch-api/overwatch_api/core.py:77: error: Argument 1 to "_add_request_parameters" has incompatible type "Callable[[AsyncOWAPI, str, Any, Any, Any, Any, Any, Any], Coroutine[Any, Any, Any]]"; expected "AsyncOWAPI"  [arg-type]
(anthok)overwatch-api/overwatch_api/core.py:96: error: Argument 1 to "_add_request_parameters" has incompatible type "Callable[[AsyncOWAPI, str, Any, Any, Any, Any, Any, Any], Coroutine[Any, Any, Any]]"; expected "AsyncOWAPI"  [arg-type]
(anthok)overwatch-api/overwatch_api/core.py:116: error: Argument 1 to "_add_request_parameters" has incompatible type "Callable[[AsyncOWAPI, str, Any, Any, Any, Any, Any, Any], Coroutine[Any, Any, Any]]"; expected "AsyncOWAPI"  [arg-type]
(anthok)overwatch-api/overwatch_api/core.py:137: error: Argument 1 to "_add_request_parameters" has incompatible type "Callable[[AsyncOWAPI, str, Any, Any, Any, Any, Any, Any], Coroutine[Any, Any, Any]]"; expected "AsyncOWAPI"  [arg-type]
(AndreiBarsan)visualqa/fabfile.py:85: error: Argument 1 to "args_to_flags" has incompatible type "Tuple[Any, ...]"; expected "List[Any]"  [arg-type]
(AndreiBarsan)visualqa/fabfile.py:242: error: Argument 1 to "args_to_flags" has incompatible type "Tuple[Any, ...]"; expected "List[Any]"  [arg-type]
(AndreiBarsan)visualqa/fabfile.py:257: error: Argument 1 to "args_to_flags" has incompatible type "Tuple[Any, ...]"; expected "List[Any]"  [arg-type]
(ikosenn)sms-log-handler/sms_log_handler/sms_handler.py:21: error: Argument 1 to "__init__" of "Handler" has incompatible type "SMSHandler"; expected "Union[int, str]"  [arg-type]
(gadelat)Bulk-Bing-Image-downloader/bbid.py:123: error: Argument 1 to "fetch_images_from_keyword" has incompatible type "BoundedSemaphore"; expected "Semaphore"  [arg-type]
(gadelat)Bulk-Bing-Image-downloader/bbid.py:134: error: Argument 1 to "fetch_images_from_keyword" has incompatible type "BoundedSemaphore"; expected "Semaphore"  [arg-type]
(WheatonCS)Lexos/lexos/receivers/rolling_window_receiver.py:202: error: Argument "milestone" to "RWAFrontEndOptions" has incompatible type "Optional[List[str]]"; expected "str"  [arg-type]
(WheatonCS)Lexos/lexos/receivers/rolling_window_receiver.py:212: error: Argument "milestone" to "RWAFrontEndOptions" has incompatible type "Optional[List[str]]"; expected "str"  [arg-type]
(WheatonCS)Lexos/lexos/helpers/general_functions.py:164: error: Argument 1 to "append" of "list" has incompatible type "List[int]"; expected "List[str]"  [arg-type]
(WheatonCS)Lexos/lexos/processors/prepare/cutter.py:284: error: Argument "seg_size" to "cut_by_characters" has incompatible type "str"; expected "int"  [arg-type]
(WheatonCS)Lexos/lexos/processors/prepare/cutter.py:288: error: Argument "seg_size" to "cut_by_words" has incompatible type "str"; expected "int"  [arg-type]
(WheatonCS)Lexos/lexos/processors/prepare/cutter.py:292: error: Argument "seg_size" to "cut_by_lines" has incompatible type "str"; expected "int"  [arg-type]
(WheatonCS)Lexos/lexos/processors/prepare/cutter.py:298: error: Argument "num_segment" to "cut_by_number" has incompatible type "str"; expected "int"  [arg-type]
(futursolo)sketchbook/tests/test_finder.py:51: error: Argument 1 to "AsyncSketchFinder" has incompatible type "int"; expected "str"  [arg-type]
(futursolo)sketchbook/tests/test_finder.py:145: error: Argument "skt_ctx" to "AsyncSketchFinder" has incompatible type "CurioSketchContext"; expected "Optional[AsyncioSketchContext]"  [arg-type]
(ThatIndividual)midas/src/resolver.py:106: error: Argument 1 to "resolveLocal" of "Resolver" has incompatible type "Assign"; expected "Ident"  [arg-type]
(ufal)neuralmonkey/scripts/tokenize_data.py:28: error: Argument 1 to "__call__" of "_StreamReader" has incompatible type "TextIO"; expected "IO[bytes]"  [arg-type]
(ufal)neuralmonkey/scripts/tokenize_data.py:29: error: Argument 1 to "__call__" of "_StreamWriter" has incompatible type "TextIO"; expected "IO[bytes]"  [arg-type]
(ufal)neuralmonkey/scripts/tokenize_data.py:30: error: Argument 1 to "__call__" of "_StreamWriter" has incompatible type "TextIO"; expected "IO[bytes]"  [arg-type]
(isudox)leetcode-solution/algorithms/python-solution/solution/least_operators_to_express_number.py:65: error: Argument 2 to "least_ops_express_target" of "Solution" has incompatible type "float"; expected "int"  [arg-type]
(pushkin-consortium)pushkin/_scripts/rancher-upgrade.py:204: error: Argument 2 to "get_service_info" has incompatible type "Union[str, RancherUpgradeException]"; expected "str"  [arg-type]
(dbrattli)OSlash/oslash/either.py:57: error: Argument 1 to "map" of "Either" has incompatible type "A"; expected "Callable[[<nothing>], <nothing>]"  [arg-type]
(audiohacked)pyBusPirate/tests/test_buspirate_rawwire.py:148: error: Argument 1 to "skip" has incompatible type "Callable[[BusPirateRawWireTest], Any]"; expected "str"  [arg-type]
(audiohacked)pyBusPirate/tests/test_buspirate_rawwire.py:170: error: Argument 1 to "skip" has incompatible type "Callable[[BusPirateRawWireTest], Any]"; expected "str"  [arg-type]
(audiohacked)pyBusPirate/tests/test_buspirate_rawwire.py:176: error: Argument 1 to "skip" has incompatible type "Callable[[BusPirateRawWireTest], Any]"; expected "str"  [arg-type]
(audiohacked)pyBusPirate/src/buspirate/base.py:121: error: Argument 1 to "write" of "BusPirate" has incompatible type "int"; expected "Optional[bytes]"  [arg-type]
(audiohacked)pyBusPirate/src/buspirate/base.py:132: error: Argument 1 to "write" of "BusPirate" has incompatible type "int"; expected "Optional[bytes]"  [arg-type]
(audiohacked)pyBusPirate/src/buspirate/base.py:199: error: Argument 1 to "write" of "BusPirate" has incompatible type "int"; expected "Optional[bytes]"  [arg-type]
(audiohacked)pyBusPirate/src/buspirate/base.py:208: error: Argument 1 to "write" of "BusPirate" has incompatible type "int"; expected "Optional[bytes]"  [arg-type]
(mattHawthorn)sk-torch/sktorch/data.py:187: error: Argument 1 to "SeqDataset" has incompatible type "Iterable[T1]"; expected "Sequence[T1]"  [arg-type]
(mattHawthorn)sk-torch/sktorch/data.py:187: error: Argument 2 to "SeqDataset" has incompatible type "Iterable[T2]"; expected "Sequence[T2]"  [arg-type]
(Galarzaa90)NabBot/nabbot.py:136: error: Argument 1 to "get_member_named" of "NabBot" has incompatible type "Union[str, int]"; expected "str"  [arg-type]
(tobiasraabe)otree_virtual_machine_manager/ovmm/prompts/parsers.py:34: error: Argument "param" to "BadParameter" has incompatible type "str"; expected "Optional[Parameter]"  [arg-type]
(tobiasraabe)otree_virtual_machine_manager/ovmm/commands/initialise.py:183: error: Argument 1 to "secho" has incompatible type "Exception"; expected "Optional[str]"  [arg-type]
(tobiasraabe)otree_virtual_machine_manager/ovmm/commands/initialise.py:183: error: Argument 2 to "secho" has incompatible type "str"; expected "Optional[IO[Any]]"  [arg-type]
(arcticicestudio)igloo/snowblocks/taskwarrior/hooks/on-modify-track-total-active-time.py:66: error: Argument 1 to "match" of "Pattern" has incompatible type "int"; expected "str"  [arg-type]
(5j9)farhangestan/app.py:20: error: Argument 1 to "maketrans" of "str" has incompatible type "Dict[str, str]"; expected "str"  [arg-type]
(gdude2002)InfoBot/bot/sections/bullet_list.py:42: error: Argument 1 to "join" of "str" has incompatible type "List[int]"; expected "Iterable[str]"  [arg-type]
(gdude2002)InfoBot/bot/sections/numbered_list.py:42: error: Argument 1 to "join" of "str" has incompatible type "List[int]"; expected "Iterable[str]"  [arg-type]
(gdude2002)InfoBot/bot/data.py:201: error: Argument 1 to "load_sections" of "DataManager" has incompatible type "List[List[Any]]"; expected "List[Union[str, str, Dict[Any, Any]]]"  [arg-type]
(juancarlospaco)css-html-js-minify/css_html_js_minify/minify.py:236: error: Argument "onerror" to "walk" has incompatible type "Optional[object]"; expected "Callable[[OSError], Any]"  [arg-type]
(oinume)dmm-eikaiwa-tsc/tsc/log.py:14: error: Argument 1 to "basicConfig" has incompatible type "**Dict[str, str]"; expected "Optional[IO[str]]"  [arg-type]
(oinume)dmm-eikaiwa-tsc/tsc/log.py:14: error: Argument 1 to "basicConfig" has incompatible type "**Dict[str, str]"; expected "Optional[Iterable[Handler]]"  [arg-type]
(dreipol)djangocms-spa/djangocms_spa/renderer_pool.py:16: error: Argument 1 to "issubclass" has incompatible type "SPAPluginMixin"; expected "type"  [arg-type]
(ForceBru)PyVM/VM/instructions/control.py:135: error: Argument 1 to "to_int" has incompatible type "int"; expected "bytes"  [arg-type]
(ForceBru)PyVM/VM/instructions/control.py:137: error: Argument 1 to "to_int" has incompatible type "int"; expected "bytes"  [arg-type]
(ForceBru)PyVM/VM/instructions/control.py:142: error: Argument 1 to "to_int" has incompatible type "int"; expected "bytes"  [arg-type]
(ForceBru)PyVM/VM/instructions/control.py:143: error: Argument 1 to "to_int" has incompatible type "int"; expected "bytes"  [arg-type]
(ForceBru)PyVM/VM/instructions/control.py:165: error: Argument 1 to "to_int" has incompatible type "int"; expected "bytes"  [arg-type]
(ForceBru)PyVM/VM/instructions/control.py:169: error: Argument 1 to "to_int" has incompatible type "int"; expected "bytes"  [arg-type]
(ForceBru)PyVM/VM/instructions/control.py:480: error: Argument 1 to "stack_push" of "CPU32" has incompatible type "bytes"; expected "int"  [arg-type]
(ForceBru)PyVM/VM/fetchLoop.py:230: error: Argument 3 to "set_bytes" of "Memory" has incompatible type "str"; expected "bytes"  [arg-type]
(ForceBru)PyVM/VM/fetchLoop.py:237: error: Argument 3 to "set_bytes" of "Memory" has incompatible type "str"; expected "bytes"  [arg-type]
(ForceBru)PyVM/VM/ELF/analyze.py:169: error: Argument 1 to "VM" has incompatible type "float"; expected "int"  [arg-type]
(renewables-ninja)gsee/gsee/climatedata_interface/pre_gsee_processing.py:53: error: Argument 2 to "convert_to_durinal" has incompatible type "Dict[Any, Any]"; expected "Tuple[Any, ...]"  [arg-type]
(renewables-ninja)gsee/gsee/climatedata_interface/pre_gsee_processing.py:56: error: Argument 2 to "clearness_index_hourly" has incompatible type "Dict[Any, Any]"; expected "Tuple[Any, ...]"  [arg-type]
(switch-education)pxt/tests/python/game.py:36: error: Argument 1 to "hex" has incompatible type "str"; expected "Union[int, _SupportsIndex]"  [arg-type]
(SunyataZero)mindfulness-at-the-computer/mc/db.py:175: error: Argument 2 to "set_schema_version" has incompatible type "int"; expected "Connection"  [arg-type]
(valerius21)ERMA17/ERMA17_alpha.py:250: error: Argument 2 to "dispatcher" has incompatible type "Callable[[object, object], object]"; expected "Dict[int, Any]"  [arg-type]
(valerius21)ERMA17/ERMA17_alpha.py:251: error: Argument 2 to "dispatcher" has incompatible type "Callable[[Any, Any], Any]"; expected "Dict[int, Any]"  [arg-type]
(valerius21)ERMA17/ERMA17_alpha.py:252: error: Argument 2 to "dispatcher" has incompatible type "Callable[[Any, Any], Any]"; expected "Dict[int, Any]"  [arg-type]
(valerius21)ERMA17/ERMA17_alpha.py:253: error: Argument 2 to "dispatcher" has incompatible type "Callable[[Any, Any], Any]"; expected "Dict[int, Any]"  [arg-type]
(valerius21)ERMA17/ERMA17_alpha.py:254: error: Argument 2 to "dispatcher" has incompatible type "Callable[[Any, Any], Any]"; expected "Dict[int, Any]"  [arg-type]
(valerius21)ERMA17/ERMA17_alpha.py:255: error: Argument 2 to "dispatcher" has incompatible type "Callable[[Any, Any], Any]"; expected "Dict[int, Any]"  [arg-type]
(valerius21)ERMA17/ERMA17_alpha.py:256: error: Argument 2 to "dispatcher" has incompatible type "Callable[[Any, Any], Any]"; expected "Dict[int, Any]"  [arg-type]
(jiadaizhao)LeetCode/0001-0100/0060-Permutation Sequence/0060-Permutation Sequence.py:16: error: Argument 1 to "join" of "str" has incompatible type "List[int]"; expected "Iterable[str]"  [arg-type]
(jiadaizhao)LeetCode/1101-1200/1106-Parsing A Boolean Expression/1106-Parsing A Boolean Expression.py:24: error: Argument 1 to "append" of "list" has incompatible type "str"; expected "bool"  [arg-type]
(jiadaizhao)LeetCode/0001-0100/0023-Merge k Sorted Lists/0023-Merge k Sorted Lists.py:39: error: Argument 1 to "heappush" has incompatible type "Tuple[Any, int, Any]"; expected "List[<nothing>]"  [arg-type]
(GoogleCloudPlatform)err-stackdriver/bigquery.py:232: error: Argument "values" to "generate_barchart" has incompatible type "str"; expected "List[Number]"  [arg-type]
(GoogleCloudPlatform)err-stackdriver/tools/server/test_server.py:44: error: Argument 2 to "TCPServer" has incompatible type "Type[MyHandler]"; expected "Callable[..., BaseRequestHandler]"  [arg-type]
(MarkdownForAcademia)markdown_for_academia/mdac/compilers/block_parser.py:43: error: Argument 1 to "load_match_obj" of "BlockParser" has incompatible type "Tuple[Any, ...]"; expected "Tuple[str]"  [arg-type]
(nginxinc)kubernetes-ingress/tests/suite/ssl_utils.py:30: error: Argument 1 to "DER_cert_to_PEM_cert" has incompatible type "Union[Dict[str, Union[str, Tuple[Tuple[Tuple[str, str], ...], ...], Tuple[Tuple[str, str], ...]]], bytes, None]"; expected "bytes"  [arg-type]
(pioneers)PieCentral/DevOps/pipeline/pipeline.py:74: error: Argument "data" to "Request" has incompatible type "Dict[Any, Any]"; expected "Optional[bytes]"  [arg-type]
(Dentosal)python-sc2/sc2/position.py:47: error: Argument 1 to "_distance_squared" of "Pointlike" has incompatible type "Pointlike"; expected "Point2"  [arg-type]
(Dentosal)python-sc2/sc2/position.py:205: error: Argument 1 to <set> has incompatible type "Pointlike"; expected "Point2"  [arg-type]
(Dentosal)python-sc2/sc2/position.py:205: error: Argument 2 to <set> has incompatible type "Pointlike"; expected "Point2"  [arg-type]
(mittagessen)kraken/kraken/repo.py:63: error: Argument 1 to "open" has incompatible type "Optional[BinaryIO]"; expected "Union[str, bytes, int, _PathLike[Any]]"  [arg-type]
(mbouchenoire)discloud/discloud/message_factory.py:21: error: Argument 1 to "update" of "dict" has incompatible type "Dict[str, float]"; expected "Mapping[str, int]"  [arg-type]
(bmassman)fake_news/fake_news/results/text_to_csv.py:62: error: Argument 3 to "parse_learner_run" has incompatible type "List[str]"; expected "List[bool]"  [arg-type]
(bmassman)fake_news/fake_news/article_learner.py:170: error: Argument 3 to "train_model" has incompatible type "object"; expected "Dict[Any, Any]"  [arg-type]
(weka-io)easypy/easypy/decorations.py:62: error: Argument 1 to "update_wrapper" has incompatible type "DecoratingDescriptor"; expected "Callable[..., Any]"  [arg-type]
(MrLeeh)pdftools/pdftools/pdftools.py:354: error: Argument 1 to "remove" has incompatible type "IO[bytes]"; expected "Union[bytes, str, _PathLike[Any]]"  [arg-type]
(AVSystem)avs_commons/tools/check-license-headers.py:43: error: Argument 1 to "map" has incompatible type overloaded function; expected "Callable[[str], Pattern[AnyStr]]"  [arg-type]
(ento)elm-doc/src/elm_doc/elm_parser/lines.py:274: error: Argument 2 to "on_source_line" of "NothingSpecial" has incompatible type "List[Type[NothingSpecial]]"; expected "List[Type[ParsingState]]"  [arg-type]
(ento)elm-doc/dodo.py:65: error: Argument 1 to "_create_tarball" has incompatible type "str"; expected "Path"  [arg-type]
(ento)elm-doc/src/elm_doc/elm_project.py:267: error: Argument 2 to "_matches_include_path" has incompatible type "_T"; expected "Path"  [arg-type]
(mokemokechicken)keras_npi/src/npi/add/lib.py:208: error: Argument 1 to "append" of "list" has incompatible type "Tuple[Any, MovePtrProgram, Tuple[int, int]]"; expected "Tuple[MovePtrProgram, Tuple[int, int]]"  [arg-type]
(mokemokechicken)keras_npi/src/npi/add/lib.py:217: error: Argument 1 to "append" of "list" has incompatible type "Tuple[Any, MovePtrProgram, Tuple[int, int]]"; expected "Tuple[MovePtrProgram, Tuple[int, int]]"  [arg-type]
(mokemokechicken)keras_npi/src/npi/add/lib.py:226: error: Argument 1 to "append" of "list" has incompatible type "Tuple[Any, MovePtrProgram, Tuple[int, int]]"; expected "Tuple[MovePtrProgram, Tuple[int, int]]"  [arg-type]
(klieret)anki-template-tester/previewtemplate.py:134: error: Argument 1 to "groups" of "Match" has incompatible type "int"; expected "str"  [arg-type]
(spoqa)geofront/geofront/backends/oauth.py:212: error: Argument 1 to "Request" has incompatible type "Mapping[str, object]"; expected "Dict[str, Any]"  [arg-type]
(jumpman24)leela-analysis-36/problem_parser.py:140: error: Argument 2 to "make_sgf" has incompatible type "str"; expected "Optional[List[Any]]"  [arg-type]
(TheReverend403)ricedb/plugins/urlinfo.py:115: error: Argument 2 has incompatible type "**Dict[str, object]"; expected <union: 9 items>  [arg-type]
(Talanor)findmyhash/findmyhash/cracker.py:51: error: Argument 1 to "decodestring" has incompatible type "str"; expected "bytes"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:83: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Type[Action]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:83: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[int, str]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:83: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[Callable[[str], <nothing>], FileType]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:83: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Iterable[<nothing>]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:83: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "bool"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:83: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "str"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:83: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Tuple[str, ...]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:84: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Type[Action]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:84: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[int, str]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:84: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[Callable[[str], <nothing>], FileType]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:84: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Iterable[<nothing>]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:84: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "bool"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:84: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "str"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:84: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Tuple[str, ...]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:85: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, str]"; expected "Union[Callable[[str], str], FileType]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:85: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, str]"; expected "bool"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:90: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Type[Action]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:90: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[int, str]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:90: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[Callable[[str], <nothing>], FileType]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:90: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Iterable[<nothing>]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:90: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "bool"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:90: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "str"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:90: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Tuple[str, ...]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:95: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Type[Action]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:95: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[int, str]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:95: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[Callable[[str], <nothing>], FileType]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:95: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Iterable[<nothing>]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:95: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "bool"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:95: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "str"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:95: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Tuple[str, ...]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:96: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Type[Action]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:96: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[int, str]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:96: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[Callable[[str], <nothing>], FileType]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:96: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Iterable[<nothing>]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:96: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "bool"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:96: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "str"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:96: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Tuple[str, ...]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:97: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Type[Action]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:97: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[int, str]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:97: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[Callable[[str], <nothing>], FileType]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:97: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Iterable[<nothing>]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:97: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "bool"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:97: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "str"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:97: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Tuple[str, ...]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:98: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, str]"; expected "Union[Callable[[str], str], FileType]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:98: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, str]"; expected "bool"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:103: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Type[Action]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:103: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[int, str]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:103: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[Callable[[str], <nothing>], FileType]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:103: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Iterable[<nothing>]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:103: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "bool"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:103: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "str"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:103: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Tuple[str, ...]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:112: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Type[Action]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:112: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[int, str]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:112: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[Callable[[str], <nothing>], FileType]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:112: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Iterable[<nothing>]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:112: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "bool"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:112: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "str"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:112: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Tuple[str, ...]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:116: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Type[Action]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:116: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[int, str]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:116: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[Callable[[str], <nothing>], FileType]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:116: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Iterable[<nothing>]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:116: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "bool"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:116: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "str"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:116: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Tuple[str, ...]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:121: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Type[Action]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:121: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[int, str]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:121: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[Callable[[str], <nothing>], FileType]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:121: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Iterable[<nothing>]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:121: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "bool"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:121: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "str"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:121: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Tuple[str, ...]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:122: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Type[Action]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:122: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[int, str]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:122: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[Callable[[str], <nothing>], FileType]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:122: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Iterable[<nothing>]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:122: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "bool"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:122: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "str"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:122: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, object]"; expected "Union[str, Tuple[str, ...]]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:130: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, str]"; expected "Union[Callable[[str], str], FileType]"  [arg-type]
(masc3d)btrfs-sxbackup/btrfs_sxbackup/cli.py:130: error: Argument 2 to "add_argument" of "_ActionsContainer" has incompatible type "**Dict[str, str]"; expected "bool"  [arg-type]
(signalfx)integrations/aws-import/awsimport.py:140: error: Argument 2 to "DocSet" has incompatible type "List[str]"; expected "Set[str]"  [arg-type]
(cvem8165)KodeFest12/tools/tools.py:29: error: Argument 1 to "MIMEText" has incompatible type "bytes"; expected "str"  [arg-type]
(rmariano)compr/tests/functional/test_smoke.py:20: error: Argument 1 to "open" has incompatible type "List[str]"; expected "Union[str, bytes, int, _PathLike[Any]]"  [arg-type]
(seisatsu)Driftwood/src/inputmanager.py:168: error: Argument 1 to "keysym" of "InputManager" has incompatible type "Union[int, str]"; expected "str"  [arg-type]
(seisatsu)Driftwood/src/configmanager.py:110: error: Argument "formatter_class" to "ArgumentParser" has incompatible type "Callable[[Any], HelpFormatter]"; expected "Type[HelpFormatter]"  [arg-type]
(seisatsu)Driftwood/tools/dbedit.py:160: error: Argument "formatter_class" to "ArgumentParser" has incompatible type "Callable[[Any], HelpFormatter]"; expected "Type[HelpFormatter]"  [arg-type]
(Thomasedv)Grabber/Modules/parameterTree.py:382: error: Argument 1 to "ParameterTree" has incompatible type "object"; expected "Dict[Any, Any]"  [arg-type]
(jfcherng)Sublime-AutoSetSyntax/SyntaxMappings.py:267: error: Argument 2 to "_get_attributes_from_xml_string" of "SyntaxMappings" has incompatible type "Iterator[Any]"; expected "List[Any]"  [arg-type]
(jfcherng)Sublime-AutoSetSyntax/SyntaxMappings.py:269: error: Argument 2 to "_get_attributes_from_yaml_string" of "SyntaxMappings" has incompatible type "Iterator[Any]"; expected "List[Any]"  [arg-type]
(ajyoon)brown/tests/test_core/test_staff_object.py:28: error: Argument 1 to "skip" has incompatible type "Callable[[TestStaffObject], Any]"; expected "str"  [arg-type]
(lipschultz)gnumeric-py/gnumeric/utils.py:96: error: Argument 1 to "row_to_spreadsheet" has incompatible type "Union[int, Tuple[int, int]]"; expected "int"  [arg-type]
(lipschultz)gnumeric-py/gnumeric/cell.py:218: error: Argument 1 to "__set_type" of "Cell" has incompatible type "str"; expected "int"  [arg-type]
(hell03end)hse_ruz/ruz/api.py:27: error: Argument 1 to "person_lessons" has incompatible type "**Dict[str, Dict[Any, Any]]"; expected "Optional[str]"  [arg-type]
(hell03end)hse_ruz/ruz/api.py:27: error: Argument 1 to "person_lessons" has incompatible type "**Dict[str, Dict[Any, Any]]"; expected "str"  [arg-type]
(hell03end)hse_ruz/ruz/api.py:27: error: Argument 1 to "person_lessons" has incompatible type "**Dict[str, Dict[Any, Any]]"; expected "Optional[int]"  [arg-type]
(hell03end)hse_ruz/ruz/api.py:256: error: Argument 2 to "isinstance" has incompatible type "_SpecialForm"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"  [arg-type]
(nathanielksmith)prosaic/prosaic/generation.py:46: error: Argument 1 to "dict" has incompatible type "Iterator[List[Any]]"; expected "Iterable[Tuple[<nothing>, <nothing>]]"  [arg-type]
(nathanielksmith)prosaic/prosaic/generation.py:46: error: Argument 1 to "map" has incompatible type "Callable[[Any], List[Any]]"; expected "Callable[[Any], Tuple[Any, Any]]"  [arg-type]
(vforgione)logging2/logging2/handlers/sockets.py:38: error: Argument 1 to "create_connection" has incompatible type "Tuple[str, str]"; expected "Tuple[Optional[str], int]"  [arg-type]
(vforgione)logging2/logging2/handlers/streaming.py:60: error: Argument "stream" to "__init__" of "StreamingHandler" has incompatible type "TextIO"; expected "TextIOWrapper"  [arg-type]
(vforgione)logging2/logging2/handlers/streaming.py:78: error: Argument "stream" to "__init__" of "StreamingHandler" has incompatible type "TextIO"; expected "TextIOWrapper"  [arg-type]
(kenkov)kovot/kovot/stream/mastodon.py:40: error: Argument 1 to "Mastodon" has incompatible type "str"; expected "Logger"  [arg-type]
(monarch-initiative)dipper/tests/test_source.py:66: error: Argument 1 to "skip" has incompatible type "Callable[[SourceTestCase], Any]"; expected "str"  [arg-type]
(enkore)i3pystatus/i3pystatus/utils/gpu.py:38: error: Argument 1 to "split" of "bytes" has incompatible type "str"; expected "Optional[bytes]"  [arg-type]
(webyneter)python-humble-utils/tests/test_commands.py:62: error: Argument 1 has incompatible type "Tuple[Any, ...]"; expected "str"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/stealth2string.py:24: error: Argument 1 to "decode" has incompatible type "str"; expected "bytes"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/walk2dict.py:32: error: Argument "onerror" to "walk" has incompatible type "Optional[object]"; expected "Callable[[OSError], Any]"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/seconds2human.py:41: error: Argument 1 to "tuple" has incompatible type "int"; expected "Iterable[Any]"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/seconds2human.py:120: error: Argument 1 to "timestamp2human" has incompatible type "float"; expected "int"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/seconds2human.py:126: error: Argument 1 to "timestamp2human" has incompatible type "float"; expected "int"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/set_desktop_launcher.py:44: error: Argument 1 to "tuple" has incompatible type "Path"; expected "Iterable[Any]"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/walk2list.py:32: error: Argument "onerror" to "walk" has incompatible type "Optional[object]"; expected "Callable[[OSError], Any]"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/bytes2human.py:34: error: Argument 1 to "tuple" has incompatible type "int"; expected "Iterable[Any]"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/get_random_pastel_color.py:194: error: Argument 2 to "unpack" has incompatible type "str"; expected "Union[array[int], bytes, bytearray, memoryview, mmap]"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/get_random_pastel_color.py:232: error: Argument 1 to "tuple" has incompatible type "float"; expected "Iterable[Any]"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/get_random_pastel_color.py:234: error: Argument 1 to "tuple" has incompatible type "float"; expected "Iterable[Any]"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/get_random_pastel_color.py:236: error: Argument 1 to "tuple" has incompatible type "float"; expected "Iterable[Any]"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/make_multiprocess.py:38: error: Argument 1 to "len" has incompatible type "int"; expected "Sized"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/url2path.py:44: error: Argument "data" to "urlopen" has incompatible type "Dict[Any, Any]"; expected "Optional[bytes]"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/url2path.py:44: error: Argument "context" to "urlopen" has incompatible type "object"; expected "Optional[SSLContext]"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/url2path.py:63: error: Argument "data" to "urlopen" has incompatible type "Dict[Any, Any]"; expected "Optional[bytes]"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/url2path.py:63: error: Argument "context" to "urlopen" has incompatible type "object"; expected "Optional[SSLContext]"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/url2path.py:78: error: Argument "data" to "urlopen" has incompatible type "Dict[Any, Any]"; expected "Optional[bytes]"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/url2path.py:78: error: Argument "context" to "urlopen" has incompatible type "object"; expected "Optional[SSLContext]"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/url2path.py:163: error: Argument 1 to "tuple" has incompatible type "Path"; expected "Iterable[Any]"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/make_datauri.py:64: error: Argument 1 to "urlsafe_b64encode" has incompatible type "str"; expected "bytes"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/make_datauri.py:76: error: Argument 1 to "img2webp" has incompatible type "Path"; expected "str"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/make_datauri.py:78: error: Argument 3 to "make" of "DataURI" has incompatible type "bytes"; expected "str"  [arg-type]
(juancarlospaco)anglerfish/anglerfish/__init__.py:217: error: Argument 1 to "enable" has incompatible type "object"; expected "Union[_HasFileno, int]"  [arg-type]
(juancarlospaco)anglerfish/examples/basic.py:176: error: Argument 2 to "walk2list" has incompatible type "str"; expected "Tuple[Any, ...]"  [arg-type]
(juancarlospaco)anglerfish/examples/basic.py:176: error: Argument 3 to "walk2list" has incompatible type "str"; expected "Tuple[Any, ...]"  [arg-type]
(juancarlospaco)anglerfish/examples/basic.py:177: error: Argument 2 to "walk2list" has incompatible type "str"; expected "Tuple[Any, ...]"  [arg-type]
(juancarlospaco)anglerfish/examples/basic.py:177: error: Argument 3 to "walk2list" has incompatible type "str"; expected "Tuple[Any, ...]"  [arg-type]
(juancarlospaco)anglerfish/examples/basic.py:178: error: Argument 2 to "walk2list" has incompatible type "str"; expected "Tuple[Any, ...]"  [arg-type]
(juancarlospaco)anglerfish/examples/basic.py:178: error: Argument 3 to "walk2list" has incompatible type "str"; expected "Tuple[Any, ...]"  [arg-type]
(juancarlospaco)anglerfish/examples/basic.py:199: error: Argument 1 to "walk2dict" has incompatible type "str"; expected "Path"  [arg-type]
(juancarlospaco)anglerfish/examples/basic.py:200: error: Argument 1 to "walk2dict" has incompatible type "str"; expected "Path"  [arg-type]
(juancarlospaco)anglerfish/examples/basic.py:201: error: Argument 1 to "walk2dict" has incompatible type "str"; expected "Path"  [arg-type]
(juancarlospaco)anglerfish/examples/basic.py:312: error: Argument 1 to "autochecksum" has incompatible type "Path"; expected "str"  [arg-type]
(martin-ejdestig)rayni-staging/tools/download_scene_data.py:140: error: Argument 1 to "_read_chunks" has incompatible type "IO[Any]"; expected "BinaryIO"  [arg-type]
(mfussenegger)cr8/cr8/java_magic.py:63: error: Argument 1 to "_find_matching_java_home" has incompatible type "Callable[[Any], Any]"; expected "Callable[[], bool]"  [arg-type]
(mfussenegger)cr8/cr8/java_magic.py:65: error: Argument 1 to "_find_matching_java_home" has incompatible type "Callable[[Any], Any]"; expected "Callable[[], bool]"  [arg-type]
(jotyGill)openpyn-nordvpn/openpyn/initd.py:168: error: Argument "inplace" to "FileInput" has incompatible type "int"; expected "bool"  [arg-type]
(jotyGill)openpyn-nordvpn/openpyn/locations.py:35: error: Argument 2 to "get_locations" has incompatible type "Dict[str, str]"; expected "str"  [arg-type]
(jotyGill)openpyn-nordvpn/openpyn/locations.py:84: error: Argument 2 to "insert" of "list" has incompatible type "List[Any]"; expected "Dict[Any, Any]"  [arg-type]
(night-crawler)django-docker-helpers/django_docker_helpers/utils.py:92: error: Argument 2 to "import_module" has incompatible type "List[str]"; expected "Optional[str]"  [arg-type]
(night-crawler)django-docker-helpers/django_docker_helpers/utils.py:361: error: Argument 1 to "coerce_str_to_bool" has incompatible type "object"; expected "Union[str, int, bool, None]"  [arg-type]
(DesertBot)DesertBot/desertbot/response.py:25: error: Argument 1 to "str" has incompatible type "Union[str, bytes]"; expected "bytes"  [arg-type]
(DesertBot)DesertBot/desertbot/response.py:29: error: Argument 1 to "str" has incompatible type "Union[str, bytes]"; expected "bytes"  [arg-type]
(google-research)morph-net/morph_net/tools/structure_exporter.py:126: error: Argument 1 to "write" of "IO" has incompatible type "str"; expected "bytes"  [arg-type]
(foozmeat)lack/lack/window.py:195: error: Argument 1 to "keypad" of "_CursesWindow" has incompatible type "int"; expected "bool"  [arg-type]
(foozmeat)lack/lack/window.py:196: error: Argument 1 to "nodelay" of "_CursesWindow" has incompatible type "int"; expected "bool"  [arg-type]
(foozmeat)lack/lack/window.py:197: error: Argument 1 to "idlok" of "_CursesWindow" has incompatible type "int"; expected "bool"  [arg-type]
(foozmeat)lack/lack/window.py:225: error: Argument 1 to "keypad" of "_CursesWindow" has incompatible type "int"; expected "bool"  [arg-type]
(foozmeat)lack/lack/window.py:226: error: Argument 1 to "nodelay" of "_CursesWindow" has incompatible type "int"; expected "bool"  [arg-type]
(foozmeat)lack/lack/window.py:227: error: Argument 1 to "idlok" of "_CursesWindow" has incompatible type "int"; expected "bool"  [arg-type]
(MichaelYusko)Bot-Chucky/bot_chucky/helpers.py:412: error: Argument 2 to "isinstance" has incompatible type "_SpecialForm"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"  [arg-type]
(ozmartian)tvlinker/tvlinker/threads.py:99: error: Argument 1 to "write" of "IO" has incompatible type "Type[BaseException]"; expected "str"  [arg-type]
(ozmartian)tvlinker/tvlinker/threads.py:179: error: Argument "data" has incompatible type "Optional[object]"; expected "Union[None, str, bytes, MutableMapping[str, Any], MutableMapping[str, Any], Iterable[Tuple[str, Optional[str]]], IO[Any]]"  [arg-type]
(Brig13Team)Operation_Kerberos/tools/validator_xml.py:134: error: Argument 1 to "skipUntil" has incompatible type "bytes"; expected "str"  [arg-type]
(Brig13Team)Operation_Kerberos/tools/validator_xml.py:138: error: Argument 1 to "skipUntil" has incompatible type "bytes"; expected "str"  [arg-type]
(Brig13Team)Operation_Kerberos/tools/validator_xml.py:144: error: Argument 1 to "skipUntil" has incompatible type "bytes"; expected "str"  [arg-type]
(Brig13Team)Operation_Kerberos/tools/validator_xml.py:159: error: Argument 1 to "skipUntil" has incompatible type "bytes"; expected "str"  [arg-type]
(Brig13Team)Operation_Kerberos/tools/validator_xml.py:163: error: Argument 1 to "checkHeader" has incompatible type "bytes"; expected "str"  [arg-type]
(Brig13Team)Operation_Kerberos/tools/validator_xml.py:165: error: Argument 1 to "checkHeader" has incompatible type "bytes"; expected "str"  [arg-type]
(jamesstidard)sanic-envconfig/setup.py:73: error: Argument "classifiers" to "setup" has incompatible type "Tuple[str, str, str, str, str]"; expected "List[str]"  [arg-type]
(madvirus)kotlin-web-site/src/search.py:151: error: Argument 1 to "get_valuable_content" has incompatible type "List[Any]"; expected "Iterator[Any]"  [arg-type]
(meraki-analytics)merakicommons/merakicommons/ghost.py:107: error: Argument 2 to "isinstance" has incompatible type "_SpecialForm"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"  [arg-type]
(meraki-analytics)merakicommons/merakicommons/ghost.py:123: error: Argument 2 to "isinstance" has incompatible type "_SpecialForm"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"  [arg-type]
(BogyMitutoyoCTL)CalculatorCV/ImageProcessing.py:53: error: Argument 1 to "len" has incompatible type "int"; expected "Sized"  [arg-type]
(shobute)go-slack/goban.py:56: error: Argument 1 to "update" of "dict" has incompatible type "Dict[Tuple[int, int], None]"; expected "Mapping[str, str]"  [arg-type]
(enchantner)python-zero/lesson_2/sample.py:7: error: Argument 1 to "my_cool_function" has incompatible type "str"; expected "int"  [arg-type]
(enchantner)python-zero/lesson_2/sample.py:7: error: Argument 2 to "my_cool_function" has incompatible type "str"; expected "int"  [arg-type]
(changyuheng)pywinwifi/src/winwifi/main.py:59: error: Argument 1 to "write" has incompatible type "RawIOBase"; expected "int"  [arg-type]
(changyuheng)pywinwifi/src/winwifi/main.py:62: error: Argument 1 to "close" has incompatible type "RawIOBase"; expected "int"  [arg-type]
(mara)mara-app/mara_app/app.py:30: error: Argument 2 to "isinstance" has incompatible type "_SpecialForm"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"  [arg-type]
(lnmds)jose/ext/vm.py:303: error: Argument 2 to "assign_and_exec" of "VM" has incompatible type "bytes"; expected "str"  [arg-type]
(SunDwarf)OWAPI/owapi/app.py:85: error: Argument 1 to "InternalServerError" has incompatible type "Exception"; expected "Optional[str]"  [arg-type]
(SunDwarf)OWAPI/owapi/blizz_interface.py:191: error: Argument 1 to "HTTPException" has incompatible type "int"; expected "Optional[str]"  [arg-type]
(SunDwarf)OWAPI/owapi/blizz_interface.py:205: error: Argument 1 to "HTTPException" has incompatible type "int"; expected "Optional[str]"  [arg-type]
(Phelimb)cbg/bigsi/tests/base.py:22: error: Argument 1 to "update" of "dict" has incompatible type "Dict[str, int]"; expected "Mapping[str, Collection[str]]"  [arg-type]
(Phelimb)cbg/bigsi/tests/base.py:28: error: Argument 1 to "update" of "dict" has incompatible type "Dict[str, int]"; expected "Mapping[str, Collection[str]]"  [arg-type]
(Phelimb)cbg/bigsi/tests/base.py:34: error: Argument 1 to "update" of "dict" has incompatible type "Dict[str, int]"; expected "Mapping[str, Collection[str]]"  [arg-type]
(tkukushkin)asynqp-consumer/src/asynqp_consumer/records.py:93: error: Argument 1 to "ConnectionParams" has incompatible type "**Dict[str, str]"; expected "int"  [arg-type]
(jr-minnaar)bitrader/bitrader/arbitrage_tools.py:361: error: Argument 5 to "arbitrage" has incompatible type "**Dict[str, str]"; expected "bool"  [arg-type]
(chengsoonong)acton/acton/plot.py:24: error: Argument 1 to "len" has incompatible type "Iterable[Any]"; expected "Sized"  [arg-type]
(rachekalmir)pyJolt/pyjolt/transforms/shiftr.py:175: error: Argument 1 to "process_sub_amp" has incompatible type "Dict[Any, Any]"; expected "TreeManager"  [arg-type]
(rachekalmir)pyJolt/pyjolt/transforms/shiftr.py:177: error: Argument 1 to "process_sub_amp" has incompatible type "Dict[Any, Any]"; expected "TreeManager"  [arg-type]
(rachekalmir)pyJolt/pyjolt/transforms/shiftr.py:180: error: Argument 1 to "process_rhs" has incompatible type "Dict[Any, Any]"; expected "TreeManager"  [arg-type]
(rachekalmir)pyJolt/pyjolt/transforms/shiftr.py:189: error: Argument 1 to "process_sub_amp" has incompatible type "Dict[Any, Any]"; expected "TreeManager"  [arg-type]
(rachekalmir)pyJolt/pyjolt/transforms/shiftr.py:189: error: Argument 2 to "process_sub_amp" has incompatible type "Dict[Any, Any]"; expected "TreeManager"  [arg-type]
(rachekalmir)pyJolt/pyjolt/transforms/shiftr.py:198: error: Argument 1 to "process_rhs" has incompatible type "Dict[Any, Any]"; expected "TreeManager"  [arg-type]
(rachekalmir)pyJolt/pyjolt/transforms/shiftr.py:201: error: Argument 1 to "process_rhs" has incompatible type "Dict[Any, Any]"; expected "TreeManager"  [arg-type]
(petervaro)cutils/pycutils/cutils/cenv.py:156: error: Argument 1 to "join" of "str" has incompatible type "StackSummary"; expected "Iterable[str]"  [arg-type]
(rr-)drill/drillsrs/cmd/stats.py:162: error: Argument 1 to "HistoryItem" has incompatible type "date"; expected "datetime"  [arg-type]
